### ISSUE TITLE
Unnecessary bindings for target_arch = "armv7"

### ISSUE THREAD

**Issue by katyo** [rust-windowing/android-ndk-rs#10]
As I know in rust `target_arch = "arm"` actually corresponding to _armv7_, so second bindings completely useless.
https://github.com/rust-windowing/android-ndk-rs/blob/a8ddfa4f7b510923cd69ded0f7e8492711b0af88/android-ndk-sys/src/lib.rs#L21-L28
Fix me if I'm wrong.

**Comment by dvc94ch** [comment]
maybe one is for thumb instructions and the other for the regular arm instructions, but not sure

**Comment by katyo** [comment]
It seems, I'm wrong:
```
$ rustup target list | grep android
aarch64-linux-android (installed)
arm-linux-androideabi (installed)
armv7-linux-androideabi (installed)
i686-linux-android (installed)
thumbv7neon-linux-androideabi
x86_64-linux-android (installed)
```
But android ndk and cargo apk supports four target archs only.

**Comment by katyo** [comment]
Rust:

| target      | notes       |
| ------------ | ------------ |
| arm-linux-androideabi | ARMv7 Android |
| armv7-linux-androideabi | ARMv7a Android |
| thumbv7neon-linux-androideabi | Thumb2-mode ARMv7a Android with NEON |

https://forge.rust-lang.org/release/platform-support.html

Android NDK:

| target | notes |
| ------- | -------- |
| armeabi-v7a | armeabi Thumb-2 VFPv3-D16 |

https://developer.android.com/ndk/guides/abis

It seems, `target_arch` should be "armv7" but it is "arm".

**Comment by katyo** [comment]
__target_arch =__

"x86"
"x86_64"
"mips"
"powerpc"
"powerpc64"
"arm"
"aarch64"

https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch

**Comment by katyo** [comment]
I look at the compiler specs, the _arch_ and _data layout_ actually is same for all 32-bit ARMs:
[arm](https://github.com/rust-lang/rust/blob/ebbb2bf37aedaaa64dfaa52ba337ca6efb6b9093/src/librustc_target/spec/arm_linux_androideabi.rs#L15), [armv7](https://github.com/rust-lang/rust/blob/ebbb2bf37aedaaa64dfaa52ba337ca6efb6b9093/src/librustc_target/spec/armv7_linux_androideabi.rs#L23), [thumbv7neon](https://github.com/rust-lang/rust/blob/ebbb2bf37aedaaa64dfaa52ba337ca6efb6b9093/src/librustc_target/spec/thumbv7neon_linux_androideabi.rs#L23).
To differentiate bindings by target kind we should check _target_feature_ (ex. `target_feature = "v7"`, `target_feature = "thumb2"`, `target_feature = "neon"`, and etc.)
But because generated bindings will be the same, so we actually don't need second section.
