### ISSUE TITLE
cargo-apk can't compile dependency (freetype-sys) using cmake

### ISSUE THREAD

**Issue by jamienicol** [rust-windowing/android-ndk-rs#100]
I'm trying to update an application from using the old version of cargo-apk (in the android-rs-glue repo) to this version, and unfortunately the build always fails when compiling the freetype-sys dependency.

```
[freetype-sys 0.13.1] thread 'main' panicked at '
[freetype-sys 0.13.1] command did not execute successfully, got: exit code: 1
[freetype-sys 0.13.1] 
[freetype-sys 0.13.1] build script failed, must exit now', /home/jamie/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
[freetype-sys 0.13.1] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `freetype-sys v0.13.1`

Caused by:
  process didn't exit successfully: `/home/jamie/src/gecko/gfx/wr/target/debug/build/freetype-sys-9a3e61826b2930fb/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/home/jamie/.cargo/registry/src/github.com-1ecc6299db9ec823/freetype-sys-0.13.1/freetype2" "-DWITH_BZip2=OFF" "-DWITH_HarfBuzz=OFF" "-DWITH_PNG=OFF" "-DWITH_ZLIB=OFF" "-DCMAKE_INSTALL_PREFIX=/home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=armv7-linux-androideabi" "-DCMAKE_C_COMPILER=/home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=armv7-linux-androideabi" "-DCMAKE_CXX_COMPILER=/home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang++" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is Clang 9.0.8
  -- The CXX compiler identification is Clang 9.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang
  -- Check for working C compiler: /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang - broken
  -- Configuring incomplete, errors occurred!
  See also "/home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out/build/CMakeFiles/CMakeOutput.log".
  See also "/home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
    The C compiler

      "/home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out/build/CMakeFiles/CMakeTmp
      
      Run Build Command(s):/usr/bin/gmake cmTC_3f8c8/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_3f8c8.dir/build.make CMakeFiles/cmTC_3f8c8.dir/build
      gmake[1]: Entering directory '/home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out/build/CMakeFiles/CMakeTmp'
      Building C object CMakeFiles/cmTC_3f8c8.dir/testCCompiler.c.o
      /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang   -ffunction-sections -fdata-sections -fPIC --target=armv7-linux-androideabi  -o CMakeFiles/cmTC_3f8c8.dir/testCCompiler.c.o -c /home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out/build/CMakeFiles/CMakeTmp/testCCompiler.c
      Linking C executable cmTC_3f8c8
      /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3f8c8.dir/link.txt --verbose=1
      /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang  -ffunction-sections -fdata-sections -fPIC --target=armv7-linux-androideabi  -rdynamic CMakeFiles/cmTC_3f8c8.dir/testCCompiler.c.o -o cmTC_3f8c8 
      /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
      /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      gmake[1]: *** [CMakeFiles/cmTC_3f8c8.dir/build.make:106: cmTC_3f8c8] Error 1
      gmake[1]: Leaving directory '/home/jamie/src/gecko/gfx/wr/target/armv7-linux-androideabi/debug/build/freetype-sys-b09c9f45f34f888d/out/build/CMakeFiles/CMakeTmp'
      gmake: *** [Makefile:140: cmTC_3f8c8/fast] Error 2
      

    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:119 (project)


  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1
```

With a bit of digging, I can see that the old version of cargo-apk [generated a cmake toolchain file](https://github.com/rust-windowing/android-rs-glue/blob/master/cargo-apk/src/ops/build/compile.rs#L57). If I copy that file somewhere and set the env variable `CMAKE_TOOLCHAIN_FILE` to point to it, then I can get past this error.

Is this something that the new cargo-apk should handle too? Or should it be handled elsewhere?

**Comment by dvc94ch** [comment]
Maybe the cmake crate should handle this? I don't think it makes sense to support every build system here.

**Comment by dvc94ch** [comment]
@jamienicol did you find a reason why it cannot be handled in the cmake crate? Otherwise I'm tending towards closing this as wont-fix

**Comment by MarijnS95** [comment]
@dvc94ch I don't think any special handling is necessary for cmake, cargo-apk already sets up the required environment variables to change to the NDK compiler.

It is therefore unsurprising `freetype-rs` examples are building correctly. Maybe @jamienicol's NDK is botched, API version 18 is pretty old afaik.

Here the cmake configure snippet in a `-vv` run:
```
[freetype-sys 0.13.1] -- The C compiler identification is Clang 11.0.5
[freetype-sys 0.13.1] -- The CXX compiler identification is Clang 11.0.5
[freetype-sys 0.13.1] -- Detecting C compiler ABI info
[freetype-sys 0.13.1] -- Detecting C compiler ABI info - done
[freetype-sys 0.13.1] -- Check for working C compiler: Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang - skipped
[freetype-sys 0.13.1] -- Detecting C compile features
[freetype-sys 0.13.1] -- Detecting C compile features - done
[freetype-sys 0.13.1] -- Detecting CXX compiler ABI info
[freetype-sys 0.13.1] -- Detecting CXX compiler ABI info - done
[freetype-sys 0.13.1] -- Check for working CXX compiler: Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++ - skipped
[freetype-sys 0.13.1] -- Detecting CXX compile features
[freetype-sys 0.13.1] -- Detecting CXX compile features - done
[freetype-sys 0.13.1] -- Creating directory me/freetype-rs/target/aarch64-linux-android/debug/build/freetype-sys-09163fd1c744f04a/out/build/include/freetype/config
[freetype-sys 0.13.1] -- Creating file me/freetype-rs/target/aarch64-linux-android/debug/build/freetype-sys-09163fd1c744f04a/out/build/include/freetype/config/ftconfig.h
[freetype-sys 0.13.1] -- Looking for unistd.h
[freetype-sys 0.13.1] -- Looking for unistd.h - found
[freetype-sys 0.13.1] -- Looking for fcntl.h
[freetype-sys 0.13.1] -- Looking for fcntl.h - found
[freetype-sys 0.13.1] -- Looking for stdint.h
[freetype-sys 0.13.1] -- Looking for stdint.h - found
[freetype-sys 0.13.1] -- Creating file me/freetype-rs/target/aarch64-linux-android/debug/build/freetype-sys-09163fd1c744f04a/out/build/include/freetype/config/ftoption.h
[freetype-sys 0.13.1] -- Configuring done
[freetype-sys 0.13.1] -- Generating done
```

It's skipping the checks, but everything compiles and links correctly after that.

@jamienicol Try a higher NDK and API version. If that succeeds, work your way down until finding the exact version that breaks.

**Comment by jamienicol** [comment]
I've tried the most recent NDK and SDK versions and still hit the same error unfortunately.

@MarijnS95 From looking at the cmake source, it looks like the reason yours skips the "Check for working C compiler" check is because the "Detecting C compiler ABI info" check succeeded. Whereas the ABI check fails on my machine, so it tries the second check too. I added some logging and can see the ABI check failed for the same reason.

What OS and cmake version are you using?

@dvc94ch I agree this doesn't really seem like it should be cargo-apk's responsibility, so feel free to close. It's probably something broken on my machine. If it turns out to be something the cmake crate can help with I'll file an issue there. In the unlikely event it turns out to be something that does feel like cargo-apk's responsibility, I can always reopen the ticket.

Thank you both for your help!

**Comment by MarijnS95** [comment]
@jamienicol Ah right! Didn't spot the `ABI info - failed` there :flushed: 

I'm on Arch Linux:

```console
$ cmake --version
cmake version 3.19.2
```

And the NDK version is `22.0.7026061`. ~Can you check if a newer NDK and/or API version works? I remember [mentioning](https://github.com/rust-windowing/android-ndk-rs/issues/29#issuecomment-636341645) `23` might be the lowest version tested ([and supported](https://github.com/rust-windowing/android-ndk-rs/issues/29#issuecomment-665359594)).~

I don't think the cmake crate can help out here. CMake should simply use the environment variables to use the appropriate (cross) compiler. I was "hoping" cargo-apk was missing something simple, ie. different folder setup, but I tried the exact same NDK and API version, surprise:

```
[freetype-sys 0.13.1] -- The C compiler identification is Clang 9.0.8
[freetype-sys 0.13.1] -- The CXX compiler identification is Clang 9.0.8
[freetype-sys 0.13.1] -- Detecting C compiler ABI info
[freetype-sys 0.13.1] -- Detecting C compiler ABI info - done
[freetype-sys 0.13.1] -- Check for working C compiler: /home/marijn/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang - skipped
[freetype-sys 0.13.1] -- Detecting C compile features
[freetype-sys 0.13.1] -- Detecting C compile features - done
[freetype-sys 0.13.1] -- Detecting CXX compiler ABI info
[freetype-sys 0.13.1] -- Detecting CXX compiler ABI info - done
[freetype-sys 0.13.1] -- Check for working CXX compiler: /home/marijn/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi18-clang++ - skipped
```

This is most likely your `cmake` version not cooperating. Aside from that the sysroot and/or `ld` might be wrong, but that's not caught here because (afaik) Cargo ever invokes the linker (`CARGO_TARGET_<triple>_LINKER`), the rest of the native chain should emit objects without linking (or combine them with `AR`).
(On that note I don't see the old `cargo-apk` set `CMAKE_LINKER` in the toolchain file either. Can you do a `-vv` run on a working build with old `cargo-apk` and compare the cmake runs?)

Perhaps interesting if we can test and potentially correct the linker setup in `cargo apk` for these cases.

**Comment by jamienicol** [comment]
[Here](https://gist.githubusercontent.com/jamienicol/9f89f8dfc63dbd5b026a378d08cf5c33/raw/653b23a1d6f4900989b23ea8ba267655ddcc0f1b/Wrench%2520with%2520old%2520cargo-apk) is the full log from the successful build using the old cargo-apk. I had to use NDK 21, as 22 wouldn't work with the old cargo-apk.

[Here](https://gist.githubusercontent.com/jamienicol/9f89f8dfc63dbd5b026a378d08cf5c33/raw/653b23a1d6f4900989b23ea8ba267655ddcc0f1b/Wrench%2520with%2520new%2520cargo-apk) is the failure using the new cargo apk. The main difference I see in the cmake invocation is the lack of a `CMAKE_TOOLCHAIN_FILE`.

Strangely I just tried creating a brand new application to see if that worked, and it did! For reference, the application I'm trying to build is [wrench](https://github.com/servo/webrender/tree/master/wrench), a tool to test webrender (Firefox's rendering engine) independently of Firefox. The new application whose build succeeds is just an empty application with webrender added as a dependency.

[Here](https://gist.githubusercontent.com/jamienicol/9f89f8dfc63dbd5b026a378d08cf5c33/raw/653b23a1d6f4900989b23ea8ba267655ddcc0f1b/New%2520app%2520with%2520new%2520cargo-apk) is the output from successfully building the new application. The main difference I can see there compared to the failing build is that `CMAKE_C_FLAGS` contains `-DANDROID`. I wonder where that is coming from, and why it isn't included when building wrench...

This made me think what could be the difference between the two applications' builds, so I tried deleting the Cargo.lock from wrench, and it worked! So there must be an outdated dependency which was causing issues.

**Comment by MarijnS95** [comment]
@jamienicol The old `cargo-apk` seems to point to clang directly (`Check for working C compiler: /home/jamie/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped`) while the new `cargo-apk` uses the wrapper script (`armv7a-linux-androideabi29-clang`) that sets up some extra flags.

Anyway, I should have perhaps asked if you ever ran `cargo clean` before? I guess deleting `Cargo.lock` might have caused a dependency update that consequently got `cmake` to delete its cache and start fresh. Or the `cmake` crate wasn't setting up some things correctly; the broken logs were using `0.1.42` whereas the working one uses `0.1.45`.

Anyway glad that you got it sorted out in the end!

**Comment by dvc94ch** [comment]
So this issue seems resolved, thanks @MarijnS95 and @jamienicol for looking into it!

**Comment by jamienicol** [comment]
Thank you both for your help!
