### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by chengchangwu** [rust-windowing/android-ndk-rs#105]
I'm trying to build hello_world with

```
cargo apk build --example hello_world
```
After compilation is finished, an error message "No such file or diretory (os error 2)" is displayed.

```
   ...
   Compiling ndk-glue v0.2.1 (/home/ccwu/Projects/android-ndk-rs/ndk-glue)
   Compiling ndk-examples v0.1.0 (/home/ccwu/Projects/android-ndk-rs/ndk-examples)
    Finished dev [unoptimized + debuginfo] target(s) in 34.32s
Error: No such file or directory (os error 2)
```

**Comment by MarijnS95** [comment]
`cargo-apk`/`ndk-build` seems to falsely use the current directory for `./target` instead of in the root of the workspace:

```
openat(AT_FDCWD, "<snip>/android-ndk-rs/ndk-examples/target/aarch64-linux-android/debug/build", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```

It has already deposited some files there as well:

```console
$ tree target
target
└── debug
    └── apk
        └── examples
            ├── AndroidManifest.xml
            └── hello_world-unaligned.apk

3 directories, 2 files
```

This only happens when `cd`'ing into `ndk-examples` to make the above command work. For the time being you can select the `ndk-examples` package while _building from the root_:

```
cargo apk build -p ndk-examples --example hello_world
```

**Comment by MarijnS95** [comment]
@chengchangwu This should be fixed by https://github.com/dvc94ch/cargo-subcommand/pull/3. Would you mind giving it a test?

**Comment by chengchangwu** [comment]
I've changed cargo-apk/Cargo.toml's cargo-subcommand to 0.4.9 and test it again. It's fixed.

**Comment by sembooooo** [comment]
I am new to rust. I have recently downloaded the docker image of rust so i assume what i have is the latest version of the rust and I still notice this problem.
Request community support here.
thank you very much in advance 😁

**Comment by dvc94ch** [comment]
Not sure why you'd use a docker image. rustup is the recommended way of installing rust. Please file a new issue describing your problem. Thanks
