### ISSUE TITLE
NDKCamera Support

### ISSUE THREAD

**Issue by drkstr101** [rust-windowing/android-ndk-rs#11]
Hello,

I apologize for using the Issues feature for general discussion, but I needed to add support for NDKCamera, and was wondering if you would be interested in a pull request. I am still learning Rust, so my PR would probably need some review and don't want to waste your time with extra work if it is unneeded or unwanted.

My plan was to add the following to `wrapper.h`:

    #include <camera/NdkCameraManager.h>
    #include <camera/NdkCameraError.h>
    #include <camera/NdkCameraDevice.h>
    #include <camera/NdkCameraMetadataTags.h>

Then create a `ndk_camera.rs` module to wrap those classes.

Would this be the correct course of action for adding NDKCamera support to my native activity, and if successful, is this something you would like me to submit a PR for?

Cheers, and thank you for your time!

~Aaron

**Comment by drkstr101** [comment]
Closing due to lack of interest.

I have started work in a standalone crate [android-ndk-camera-rs](https://gitlab.com/waweb/android-ndk-camera-rs), in case anyone else may find it useful.

**Comment by goddessfreya** [comment]
cc @dvc94ch

**Comment by dvc94ch** [comment]
That seems like a sensible approach. I'm certainly interested in this for https://github.com/dvc94ch/flutter-qrcode-plugin, have you considered adding support to https://github.com/oli-obk/camera_capture?

**Comment by drkstr101** [comment]
I ended up on these:

    #include <camera/NdkCameraCaptureSession.h>
    #include <camera/NdkCameraDevice.h>
    #include <camera/NdkCameraError.h>
    #include <camera/NdkCameraManager.h>
    #include <camera/NdkCameraMetadata.h>
    #include <camera/NdkCameraMetadataTags.h>
    #include <camera/NdkCameraWindowType.h>
    #include <camera/NdkCaptureRequest.h>

Please let me know if there is anything missing from there you may need.

**Comment by dvc94ch** [comment]
I haven't really looked into the camera api yet

**Comment by drkstr101** [comment]
I've started incubating the library here: https://github.com/drkstr101/CartoonifyIt

It will essentially be the basic NDKCamera sample app ported to rust. Once it's stable I will release it as its own crate.
