### ISSUE TITLE
Cargo-apk allows run apk only from the workspace root

### ISSUE THREAD

**Issue by Gordon-F** [rust-windowing/android-ndk-rs#115]
Currently, `cargo-apk` allows run apk only from workspace root. It would be awesome if `cargo-apk` can run apk from example project.

Test example:
https://github.com/Gordon-F/gfx/tree/bf7bdc12f93485616f6dd06dd574c2e7afe99e16

```bash
cd gfx/
cargo apk run --package quad_android --target x86_64-linux-android --features gl                                                                               
error: --features is not allowed in the root of a virtual workspace
```

```bash
cd gfx/examples/quad_android
cargo apk run --package quad_android --target x86_64-linux-android --features gl                                                                               
   Compiling quad_android v0.1.0 (/Users/indish/Dev/RustProjects/gfx/examples/quad_android)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 18s
Error: No such file or directory (os error 2)
```

**Comment by MarijnS95** [comment]
Hi @Gordon-F, thanks for reporting this!

I think however that we might have fixed this issue last week following https://github.com/rust-windowing/android-ndk-rs/issues/105. Can you update `cargo-apk` with the latest version of `cargo-subcommand` (by running `cargo install --force cargo-apk`) and let us know whether this remains to be a problem?

**Comment by Gordon-F** [comment]
@MarijnS95 Thank you for your extremely quick answer! The issue is fixed with new update!
