### ISSUE TITLE
ndk-glue does not handle NativeWindow lifecycle correctly

### ISSUE THREAD

**Issue by maciejgodek** [rust-windowing/android-ndk-rs#117]
As far as I understand, `ndk-glue`'s `NativeActivity` callbacks make it impossible or at least very hard to handle the `NativeWindow` lifecycle in a manner that conforms with the Android documentation. The chief offending callback is [`on_window_destroyed`](https://github.com/rust-windowing/android-ndk-rs/blob/13914ef4c9ff39af289e26bb2f5d1ff12f91ca18/ndk-glue/src/lib.rs#L242).

[`ANativeActivityCallbacks` documentation](https://developer.android.com/ndk/reference/struct/a-native-activity-callbacks#struct_a_native_activity_callbacks_1a6aaafbbfae4c0ac066b9d61ebb3ab97f) seems to demand that `NativeWindow` cleanup code be executed in a synchronized manner, i.e. before the callback returns. For example, one might wish to ensure OpenGL is done drawing and destroy the associated `EGLSurface`.

[NDK `android_native_app_glue`](https://cs.android.com/android/platform/superproject/+/master:prebuilts/ndk/r21/sources/android/native_app_glue/android_native_app_glue.c) appears to follow this guideline, cf. especially how lifecycle event handling is split into pre-user-callback and post-user-callback parts (lines 89 and 146 respectively).

EDIT: for added context, compare [example usage](https://github.com/android/ndk-samples/blob/master/native-activity/app/src/main/cpp/main.cpp) of NDK `android_native_app_glue` feature.

**Comment by MarijnS95** [comment]
Correct!

I think the most interesting lines are [306-308](https://cs.android.com/android/platform/superproject/+/master:prebuilts/ndk/r21/sources/android/native_app_glue/android_native_app_glue.c;l=306-308;drc=master;bpv=1;bpt=1) though, showing that `android_app_set_window` (called from ` onNativeWindowDestroyed`) indeed blocks and waits for the application to terminate.

At the same time it seems unfair to pull `NATIVE_WINDOW` from under the application, `native_window()` would panic in that case.

I've been thinking about fixing this before, and it probably comes down to delivering this event to the application in a different way that allows us to make sure their cleanup handler has ran, surrounded by similar synchronization primitives.

**Comment by MarijnS95** [comment]
Interesting to note that their `on_window_created` handler first checks if the previous window was cleaned up, and sends a destroy message for it otherwise.

**Comment by maciejgodek** [comment]
Thanks for the quick confirmation! I'd love to try to put a pull request together, but: I'm pretty new at Rust, and as you say, it would be necessary to come up with better synchronization with user code, impacting e.g. winit. I'd probably need a fair amount of hand-holding.

**Comment by maciejgodek** [comment]
> Interesting to note that their `on_window_created` handler first checks if the previous window was cleaned up, and sends a destroy message for it otherwise.

That is interesting! Is it just me, or does it seem to imply that it's possible for two `on_window_created` callbacks to fire without an intervening `on_window_destroy`? I suppose it raises the question whether the Android devs “know something we don't” and so one should cargo-cult it just in case.

**Comment by maciejgodek** [comment]
> Interesting to note that their `on_window_created` handler first checks if the previous window was cleaned up, and sends a destroy message for it otherwise.

I'm not sure that's the case. It seems that the function [`android_app_set_window()`](https://cs.android.com/android/platform/superproject/+/master:prebuilts/ndk/r21/sources/android/native_app_glue/android_native_app_glue.c;drc=ac7267403123fe76a49cf340ecda810c721ae3cb;l=297) just gets reused both for `on_window_created` and `on_window_destroyed`, relying on some undocumented invariants to do the right thing. It's just unnecessarily dense code.

**Comment by maciejgodek** [comment]
As far as solutions for `ndk-glue` go — assuming there is no actual black magic involved: might it not suffice to add a one-shot channel / fence of some kind that user code must notify when done with `NativeWindow` cleanup? There are actually only two types of events that need this kind of synchronization (`on_window_destroyed` and `on_save_instance_state`), so ad-hoccing them in one way or another seems like a passable choice.

**Comment by MarijnS95** [comment]
@maciejgodek Correct, in hindsight it seems more of a simplification than an actual paranoid attempt to make sure no window is leaked. For the same reasons I'd either like to see the same behaviour (clean up the window if non-null before assigning), or an assertion.

No matter the implementation it seems like `onInputQueueDestroyed` and `onNativeWindowRedrawNeeded` need synchronization as well; we might want to spend some time flushing out a high-level representation of these rather than applying a simple hack. I don't want to restrict API users too much; at the same time I don't want an application to deadlock because someone forgot to signal `ndk-glue` that one of the few "synchronous" events has been processed. That usually ends in some closure running within some locked context, though.

**Comment by maciejgodek** [comment]
It took me an evening or three to get a minimal "hello triangle" app running on Android to have a basic debugging environment & get a better handle on EGL behavior. (I hacked bits of glutin together with glow-rs.) I can now try to implement your suggestion, should have something to share in a few days.

My basic idea is to give up on the UNIX pipe of single byte enums as event queue (as simple and low-overhead as it is). Instead I suggest a queue of Rust enums, much like what winit uses for user events. For events providing a new resource and/or requiring synchronization with the callback, the enum variant will contain a SyncEventContext<T>, something along the lines of:

```rust
pub struct SyncEventContext<T> {
    done_notifier: Sender<()>,
    payload: Arc<Mutex<T>> 
}

impl<T> SyncEventContext<T> {
    pub fn handle<F: FnOnce(&T)>(self, f: F) {
        {
            let lock = self.payload.lock().unwrap();
            f(&lock);
        }
        let _ = self.done_notifier.send(());
    }
}
```

Any thoughts?

**Comment by MarijnS95** [comment]
@maciejgodek The advantage of the pipe is that can easily integrate with Androids `Looper`, immediately making the source clear. With this approach you'll need to `.wake()` the `Looper` and figure out where that wake came from; similar to the issue discussed in https://github.com/rust-windowing/winit/pull/1822#issuecomment-760769960.

At this point we should probably create a higher-level wrapper in `ndk-glue` around `.wake()` and retrieving event source + possible extra data, taking generics that can be passed through an atomic queue or `channel`.

Otherwise these events might be triggered by a single-byte write on the original UNIX pipe (or a new one with distinct `ident`) in the form of a new `Event::SyncEvent` that the consumer should retrieve/process from that queue. From an `ndk-glue` perspective that could be wrapped in a `struct` that signals `done_notifier` when dropped. You could possibly mix the `Mutex` with a `Condvar` to achieve this.

**Comment by maciejgodek** [comment]
Ok, so a higher-level wrapper with a queue, `wake()`, and identifiable event source.

Here's what I've been thinking: all you need to plug into the Looper is a file descriptor that can be slept on/polled, right? I thought we could build it around `eventfd` instead of `pipe`.  As for the queueing mechanism, you could use `Arc<Mutex<VecDeque>>` to start with and then maybe something cleverer / more tightly integrated with the waking mechanism.

**Comment by maciejgodek** [comment]
I've put together something matching the above description in PR  #121. Not sure if it's changing too much in the API. I also accidentally added a new method of building another event queue attached to the looper (e.g. user event queue in winit) and a method of sending redraw events.

I've got a winit branch that works with this API, will push it tomorrow, and try to adapt glutin for it next week.

**Comment by dvc94ch** [comment]
Why is there a problem? `native_window` returns a guard and `on_window_destroyed` takes a write lock, which will block until all read locks are dropped.

I think the problem is with glutin when trying to write correct code (no one seems interested in the new glutin that fixes these issues in the next branch) or people trying to cheat the *very* clear api in some way (keeping raw dangling pointers to native window around)

**Comment by maciejgodek** [comment]
Huh. That... might work. I'm not (yet) sure it does.

Just to be clear, for that to work the way you describe, the user (e.g. glutin) would have to hang on to their `ReadLockGuard` from the time they first started using the `NativeWindow` for as long as they wish to continue using it or any objects derived from it, such as `EGLSurface`.

But in that case the user needs a way of knowing that the `NativeWindow` is about to go away. Currently, `on_window_destroyed` sends the `Destroyed` event *after* trying to obtain write access to the `RwLock`. What's worse, it sends the notification to the winit even loop, which does not seem to notify glutin in any way (at least on `master`).

But let me dig around some more, I might be fundamentally misunderstanding something about the whole ecosystem. :smile:

**Comment by dvc94ch** [comment]
goddessfreya the previous glutin maintainer last made contact in feb 2020, never to be heard from again, and taking the glutin improvements with her to the graveyard of dead code.

- https://github.com/rust-windowing/glutin/tree/v0.23_reworks
- https://github.com/rust-windowing/glutin/pull/1274
- https://github.com/rust-windowing/glutin/issues/1271

**Comment by maciejgodek** [comment]
Ok, I'm going to read it all carefully and close my PR for now to reduce confusion.

FWIW I still think there's either a race condition or a potential deadlock in [`on_window_destroyed`](https://github.com/rust-windowing/android-ndk-rs/blob/13914ef4c9ff39af289e26bb2f5d1ff12f91ca18/ndk-glue/src/lib.rs#L246). The notification should be sent *before* obtaining a write lock, so clients have a chance to drop their long-lived read locks, which they should be holding if they have created new objects dependent on `NativeWindow`.

**Comment by MarijnS95** [comment]
@maciejgodek Did you manage to look into this yet?

I indeed agree that the notification should be sent _before_ grabbing the write lock. Winit should hold on to the read lock as soon as `raw_window_handle` is called, and drop it on `WindowDestroyed` _after_ it finished handling that event in user code. Alternatively Winit can grab and cache the lock in `WindowCreated` and serve from there if `raw_window_handle` is called. At that point we can only assume user code stops using the window and any implicit dependencies like Vulkan surfaces/swapchains. Reworking Winit to serve the window in `::Resumed` and coming up with complicated structures to prevent using it after `::Suspended` probably isn't worth it, nor really possible.

**Comment by maciejgodek** [comment]
I've tried digging into last year's attempted `glutin` rework but it seems sufficiently different from what master that it's mostly a curiosity. :( I'm still not sure how exactly it allows users to keep an `EGLContext` alive while windows come and go. I'll give it another read some day — I had trouble locating all the dependencies.

As for the more immediate problem, I agree. The reasonable thing is for `winit` to extend the lifetime of the native window until after the user handles its `Suspended` event. In that case, `android-ndk-rs` just needs to make that possible without a race or deadlock, which should require changing approximately two lines of code. :) I will try to put together the two PRs this weekend.

What worries me is whether various `winit` wrappers (including but not limited to `glutin`) are currently capable of intercepting the `Suspended` event and correctly destroying the implicit dependencies of the `NativeWindow` without forcing the user to recreate the entire graphics context, which can be quite expensive. But that should probably be discussed elsewhere.
