### ISSUE TITLE
Android 10 does not support

### ISSUE THREAD

**Issue by shijunti19** [rust-windowing/android-ndk-rs#122]
Android 10 does not support

**Comment by MarijnS95** [comment]
What does Android 10 not support? Inclined to close this issue without more information.

**Comment by shijunti19** [comment]
@MarijnS95 
`
   Compiling ndk v0.2.1
   Compiling ndk v0.3.0 (F:\web\xiaolu\rust\android\android-ndk-rs\ndk)
   Compiling ndk-glue v0.2.1
   Compiling winit v0.24.0
   Compiling ndk-glue v0.3.0 (F:\web\xiaolu\rust\android\android-ndk-rs\ndk-glue)
   Compiling ndk-examples v0.1.0 (F:\web\xiaolu\rust\android\android-ndk-rs\ndk-examples)
    Finished dev [unoptimized + debuginfo] target(s) in 48.58s
 'lib/arm64-v8a/libhello_world.so'...
Verifying alignment of F:\web\xiaolu\rust\android\android-ndk-rs\target\debug\apk\examples\hello_world.apk (4)...
      49 AndroidManifest.xml (OK - compressed)
     880 lib/arm64-v8a/libhello_world.so (OK - compressed)
Verification succesful
* daemon not running; starting now at tcp:5037
* daemon started successfully
Performing Push Install
adb: error: failed to get feature set: no devices/emulators found
Error: Command `E:\\ProgramFiles\\Android\\Sdk\\platform-tools\\adb.exe install -r F:\\web\\xiaolu\\rust\\android\\android-ndk-r
s\\target\\debug\\apk\\examples\\hello_world.apk` had a non-zero exit code.
`

**Comment by MarijnS95** [comment]
> ```batchfile
> adb: error: failed to get feature set: no devices/emulators found
> ```

You may want to attach an Android device or start the emulator. Make sure the appropriate drivers and such are installed.

The rest of the logs show that android-ndk works as expected and created a valid APK with the right binaries. By the way, don't try to mix different versions of the same crate (`v0.2.1` and `v0.3.0` of our crates), that's asking for lots and lots of trouble (at runtime).
