### ISSUE TITLE
Does it automatically use Java code before compiling to machine code or do I have to do something manually?

### ISSUE THREAD

**Issue by Joe23232** [rust-windowing/android-ndk-rs#124]
Hi, I  wanted to know does this crate automatically use Java code before compiling to machine code or do I have to do something manually like call something through Java?

**Comment by MarijnS95** [comment]
No Java code is involved, Android native activities only need a library (`.so`) and `AndroidManifest.xml`. Under the hood Android itself has a [Java `NativeActivity` class](https://developer.android.com/reference/android/app/NativeActivity) that loads and calls into this library.

As per the `README` all you need is `cargo apk build` (and a valid NDK toolchain installed).
