### ISSUE TITLE
Cannot run hello_world example

### ISSUE THREAD

**Issue by Wolfman13** [rust-windowing/android-ndk-rs#130]
I downloaded the repository and build the hello_world example, this worked perfectly with the output of:

> Finished dev [unoptimized + debuginfo] target(s) in 0.31s
>  'lib/arm64-v8a/libhello_world.so'...
> Verifying alignment of D:\Development\Rust\Android\android-ndk-rs-master\target\debug\apk\examples\hello_world.apk (4)...
>       49 AndroidManifest.xml (OK - compressed)
>     1016 lib/arm64-v8a/libhello_world.so (OK - compressed)
> Verification successful

But then when I try to run the code on the android emulator I end up with this issue:

> 
> Finished dev [unoptimized + debuginfo] target(s) in 0.31s
>  'lib/arm64-v8a/libhello_world.so'...
> Verifying alignment of D:\Development\Rust\Android\android-ndk-rs-master\target\debug\apk\examples\hello_world.apk (4)...
>       49 AndroidManifest.xml (OK - compressed)
>     1016 lib/arm64-v8a/libhello_world.so (OK - compressed)
> Verification succesful
> Performing Incremental Install
> Serving...
> All files should be loaded. Notifying the device.
> Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> Performing Streamed Install
> adb: failed to install D:\Development\Rust\Android\android-ndk-rs-master\target\debug\apk\examples\hello_world.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> Error: Command 'C:\\Users\\jeanj\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe install -r D:\\Development\\Rust\\Android\\android-ndk-rs-master\\target\\debug\\apk\\examples\\hello_world.apk' had a non-zero exit code.

I have googled the issue but all the solutions require me to change a build.gradle file so I am not quite sure those solutions are applicable in this situation.

I am running the example on a Windows 10 laptop with rustup 1.23.1, rustc 1.50.0, and ndk 23.0.7123448 if that helps.

**Comment by MarijnS95** [comment]
The Android emulator runs x86 apks, not those for `arm64-v8a`. You'll have to pick the appropriate [`--target`](https://doc.rust-lang.org/nightly/rustc/platform-support.html) and try again.

**Comment by Wolfman13** [comment]
Okay so I tried your suggestion, and tried using the command: "cargo apk run --target x86_64-linux-android --example hello_world" as well as "cargo apk run --example hello_world --target x86_64-linux-android", both gave the same error:

> 
> Finished dev [unoptimized + debuginfo] target(s) in 0.30s
>  'lib/x86_64/libhello_world.so'...
> Verifying alignment of D:\Development\Rust\Android\android-ndk-rs-master\target\debug\apk\examples\hello_world.apk (4)...
>       49 AndroidManifest.xml (OK - compressed)
>     1013 lib/x86_64/libhello_world.so (OK - compressed)
> Verification succesful
> Performing Incremental Install
> Serving...
> All files should be loaded. Notifying the device.
> Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> Performing Streamed Install
> adb: failed to install D:\Development\Rust\Android\android-ndk-rs-master\target\debug\apk\examples\hello_world.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> Error: Command 'C:\\Users\\jeanj\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe install -r D:\\Development\\Rust\\Android\\android-ndk-rs-master\\target\\debug\\apk\\examples\\hello_world.apk' had a non-zero exit code.

**Comment by Wolfman13** [comment]
Okay, I finally got it figured out, the command I had to use for the emulator to run is: "cargo apk run --example hello_world --target i686-linux-android". Thank you for pointing me in the right direction
