### ISSUE TITLE
Error: Path "android-sdk/ndk/23.0.7196353/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar" doesn't exist.

### ISSUE THREAD

**Issue by evant** [rust-windowing/android-ndk-rs#135]
Not seeing this file in ndk version 23, it is present in version 22.

**Comment by MarijnS95** [comment]
Thank you for reporting! NDK r22 deprecated GNU binutils in favour of LLVM's, and those have finally been removed in [NDK r23](https://github.com/android/ndk/wiki/Changelog-r23). This should be fixed by #137, please give it a try!
