### ISSUE TITLE
support using a user supplied signing key

### ISSUE THREAD

**Issue by dvc94ch** [rust-windowing/android-ndk-rs#140]
at work we have some custom android builds using gradle with a java wrapper. there is no real business case to change what already works, but using a user supplied signing key would be a requirement.

**Comment by MarijnS95** [comment]
> there is no real business case to change what already works

Not sure whether this applies to your app or `cargo-apk`... But hardcoding a debug key like we do right now means `cargo-apk` is not production ready yet, that's only for hobbyists and developers playing around.

**Comment by dvc94ch** [comment]
Well, I might one day port our setup if I have a week of vaccation and no other projects on my list. Not sure, haven't put much thought into it yet. Since we release via ci, a cli option would be fine.

**Comment by MarijnS95** [comment]
Implemented in #299!
