### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by gravit22** [rust-windowing/android-ndk-rs#143]
Can't compile for some reason.

`   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.71
   Compiling serde v1.0.125
   Compiling ident_case v1.0.1
   Compiling fnv v1.0.7
   Compiling strsim v0.9.3
   Compiling libc v0.2.94
   Compiling log v0.4.14
   Compiling jni-sys v0.3.0
   Compiling cfg-if v1.0.0
   Compiling ndk-sys v0.2.1
   Compiling lazy_static v1.4.0
   Compiling quote v1.0.9
   Compiling toml v0.5.8
   Compiling proc-macro-crate v0.1.5
   Compiling darling_core v0.10.2
   Compiling thiserror-impl v1.0.24
   Compiling derivative v2.2.0
   Compiling num_enum_derive v0.5.1
   Compiling darling_macro v0.10.2
   Compiling darling v0.10.2
   Compiling thiserror v1.0.24
   Compiling ndk-macro v0.2.0
   Compiling num_enum v0.5.1
   Compiling ndk v0.3.0
   Compiling ndk-glue v0.3.0
   Compiling android v0.1.0 (/home/mykhailo/Rust/android)
error: linking with `/home/mykhailo/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang` failed: exit code: 1
  |
  = note: "/home/mykhailo/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--allow-multiple-definition" "-Wl,--eh-frame-hdr" "-L" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.2dpxq7q85vvn2bgy.rcgu.o" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.313t75cmmkq8os3p.rcgu.o" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.3myg2ifwqj0dzum7.rcgu.o" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.3ov3im0mtv1ji5hd.rcgu.o" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.4pg58o04n4rfncfe.rcgu.o" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.ov0rqus56whg5gv.rcgu.o" "-o" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libandroid.so" "-Wl,--version-script=/tmp/rustcHdOQko/list" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/android.16lldno153n3o9wf.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps" "-L" "/home/mykhailo/Rust/android/target/debug/deps" "-L" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib" "-Wl,-Bstatic" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libndk_glue-d3ec144970504a46.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/liblibc-a97ee389ab6e73ee.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libndk-7dd9dd7f4132df33.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libjni_sys-ba957f9cc563be8c.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libndk_sys-d2bef1febc60432b.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libthiserror-2bb99a7cfb966f89.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libnum_enum-4d6991c69c2895cf.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/liblog-9c6ba3ac3d325659.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/libcfg_if-76feeb5d2a875ab8.rlib" "/home/mykhailo/Rust/android/target/aarch64-linux-android/debug/deps/liblazy_static-b51125e8ab9c415b.rlib" "-Wl,--start-group" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libstd-16a547e3e84c5d9b.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libpanic_unwind-d2f930f9ff445b20.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libminiz_oxide-37e0a69203933d0d.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libadler-0deee57faf38f52c.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libobject-fb7e23c6c57fda11.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libaddr2line-68888a62e1e4a241.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libgimli-2593ac7ecd6522fa.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/librustc_demangle-a4514ea058b0e0df.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libhashbrown-4c022c13ced4b986.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/librustc_std_workspace_alloc-803806d1284edc9a.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libunwind-2ca706560a5f56f8.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libcfg_if-64f03a56a6c7b0aa.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/liblibc-c0a2296b196cea1f.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/liballoc-6a51bfed66066a03.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/librustc_std_workspace_core-11b20aebd859cbf2.rlib" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libcore-311d527f953f832d.rlib" "-Wl,--end-group" "/home/mykhailo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libcompiler_builtins-4cf27a8e334e7343.rlib" "-Wl,-Bdynamic" "-landroid" "-ldl" "-llog" "-lgcc" "-lc" "-lm"
  = note: ld: error: /home/mykhailo/Rust/android/target/debug/deps/libandroid.so is incompatible with aarch64linux
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `android`

To learn more, run the command again with --verbose.
Error: Command `cargo build --target aarch64-linux-android` had a non-zero exit code.
`

**Comment by MarijnS95** [comment]
> `Compiling android v0.1.0 (/home/mykhailo/Rust/android)`

That seems like a very similar issue to #38. Name your project something that's _not_ `"android"`, and it should work! :pray:
