### ISSUE TITLE
Can't see "hello world" on the screen

### ISSUE THREAD

**Issue by gravit22** [rust-windowing/android-ndk-rs#144]
I am trying basic example, and it compiles very well, but when it runs on android it just doesn't work properly.
![image](https://user-images.githubusercontent.com/33228017/116647896-60d0b580-a984-11eb-8aa9-cd091fc6aff9.png)

**Comment by MarijnS95** [comment]
What do you expect from the example? This is a bare-bones application that prints a line to the log and then exits. It does not set up a looper nor reads from the input queue (resulting in ANR), you'll have to do all that by yourself (see for example #111, this should be made into an example at some point) or use an existing windowing library like [winit](https://github.com/rust-windowing/winit/).
