### ISSUE TITLE
ndk directory structure changed?

### ISSUE THREAD

**Issue by dvc94ch** [rust-windowing/android-ndk-rs#155]
Started getting this ci failure. Looks like google released a new ndk with a changed directory structure. Or github-actions changed something.

Error: Path `"/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"` doesn't exist.

**Comment by MarijnS95** [comment]
What's the version of this `ndk-bundle`? Is it one of the [R23 betas/RCs](https://github.com/android/ndk/wiki#ndk-r23)? If so, keep in mind that needs a newer Rust with the fix for https://github.com/rust-windowing/android-ndk-rs/issues/149, too.

**Comment by dvc94ch** [comment]
according to [0] the github actions runner comes with `21.4.7075529` preinstalled. So that would be a pretty "old" version. I wonder what else could have changed.

- [0] https://github.com/actions/virtual-environments/blob/ubuntu20/20210718.1/images/linux/Ubuntu2004-README.md

**Comment by MarijnS95** [comment]
Same error when re-running the CI on `master`, which was succeeding before. Could https://github.com/actions/virtual-environments/commit/f1ab1bd12f5ef0704fde4d7944c09fecd026a564 have had an impact here?

**Comment by MarijnS95** [comment]
Oh I see - I just had this happen locally. I have the Android 31 platform installed, but NDK 22.1 (nor 21.4 by definition) support it. We should rewrite:

https://github.com/rust-windowing/android-ndk-rs/blob/14a8c9c93fc0f4795f8564b8675ba57ba6f9cf01/ndk-build/src/ndk.rs#L56-L66

To take the intersection with platforms the NDK actually supports. We can find that with `toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/<triple>/<android API version>/` existence, for example.
