### ISSUE TITLE
drop failure in favor of thiserror

### ISSUE THREAD

**Issue by dvc94ch** [rust-windowing/android-ndk-rs#16]

**Comment by francesca64** [comment]
@dvc94ch can you elaborate on the motive for this? I haven't really been keeping up with all the progress on error ergonomics.

**Comment by dvc94ch** [comment]
failure was a stepping stone that lead to redesigning the std::error::Error trait. thiserror is compatible, it basically just implements the display, error and optionally From traits, with less typing effort. It is compatible with implementing those traits manually so interopability should be better. Failure is unmaintained.

**Comment by francesca64** [comment]
Ah, that sounds great then. Thanks for explaining.
