### ISSUE TITLE
New release with threading fixes?

### ISSUE THREAD

**Issue by iamralpht** [rust-windowing/android-ndk-rs#164]
Would it be possible to make a new release on crates.io (and then update winit)? The recent threading fixes in ndk_glue seem like very important improvements. If it would help to have a PR that bumps the versions then I can create one.

**Comment by MarijnS95** [comment]
Looks like the changes weren't added to `CHANGELOG.md`, hence went unnoticed for a while. We'll try to release them as patch version with #165 so that `winit` doesn't need to change anything as per semver.

**Comment by iamralpht** [comment]
Wow, thanks so much for doing this so quickly!

**Comment by MarijnS95** [comment]
@iamralpht No problem, I'm actually quite ashamed it took as long as it did as we're usually releasing changes on time.

Unfortunately the crate failed to publish as I misjudged a dependency on the `ndk` crate, see https://github.com/rust-windowing/android-ndk-rs/pull/165#issuecomment-889346711. I'll re-evaluate and hopefully have the release up later today.
