### ISSUE TITLE
How can I modify the AndroidManifest.xml

### ISSUE THREAD

**Issue by VZout** [rust-windowing/android-ndk-rs#17]
I want to modify the AndroidManifest.xml. Is there a existing way to add permissions for example?

**Comment by dvc94ch** [comment]
Same as cargo-apk. The Cargo.toml should be compatible. I don't recall if to 100% or if some small changes need to be made.
I'd suggest looking at the code as documentation is lacking. The code is very straightforward.

**Comment by VZout** [comment]
Thanks!

**Comment by anoushk1234** [comment]
> Thanks!

Hey @VZout did you figure this out? for some reason android is blocking my network requests and apparently i need to add `<uses-permission android:name="android.permission.INTERNET"/>` acc to this [SO post](https://stackoverflow.com/a/55548864/13749032)
