### ISSUE TITLE
Is the "Rust+Android NDK" approach suitable and production-ready compared with the traditional C++ approach? i.e. Can I use it in real-world app in production environment?

### ISSUE THREAD

**Issue by fzyzcjy** [rust-windowing/android-ndk-rs#184]
Hi thanks for this lib! I wonder whether the "Rust+Android NDK" approach is suitable and production-ready compared with the traditional C++ approach? i.e. Can I use it in real-world app in production environment?

For example, will there be performance issues for performance-critical programs? Will the generated size be too big? Will there be hidden traps (because the whole toolchain is not that mature)?

**Comment by dvc94ch** [comment]
someone has to be the first. I don't know why it would be slower than c++ code. closing as it's unlikely to get a better answer.

**Comment by fzyzcjy** [comment]
Oh months have passed. I have already used it in production environment and it works pretty well. Except that the generated binary is a bit larger (but acceptable)
