### ISSUE TITLE
Stdout and err redirection

### ISSUE THREAD

**Issue by Yuri6037** [rust-windowing/android-ndk-rs#185]
Hello,

I've read the ndk-glue lib and I found something that could be a problem for certain apps.

Redirecting stdout and stderr to android log API is a good idea but your implementation uses 2 threads which means that applications made with ndk-glue will consume more CPU time and power; leaving fewer resources for highly-parallel and performance critical applications.

Could you please consider putting all the stdout stderr redirection behind a compile time feature?

**Comment by Yuri6037** [comment]
Well my bad for yesterday typo for the number of threads; it was very late I wasn't paying much attention. I really meant the first thread with the pipe read and dup2. I know it does a blocking read.

The problem is it still creates a thread even though it may be issuing a blocking read. This will still consume CPU time when the blocking read will return. IE if your app contains crates which calls println enough you can get a problem.

And in all cases this will consume as you said some memory, power and possibly some time lost in the kernel at handling an output redirection which should clearly not exist in release builds. Even if the performance loss is negligable as you said, there is still gonna be a performance impact even small but there will be one which is totally (in my application) useless. I hate to have to sacrifice an resources only for the convenience of a feature that I won't even use.

I will probably consider using https://github.com/chicken-mobile/android-ndk/blob/master/android-native-app/android_native_app_glue.c.

**Comment by dvc94ch** [comment]
agree with @MarijnS95 that there isn't much to be gained here. Closing for now.
