### ISSUE TITLE
Bump ndk-glue release?

### ISSUE THREAD

**Issue by hrydgard** [rust-windowing/android-ndk-rs#199]
I'd like to bump the ndk-glue dependency of some other crates to sync things up, so would be nice with a new release.

Any planned soon?

**Comment by MarijnS95** [comment]
https://github.com/rust-windowing/android-ndk-rs/pull/191 Not even planned, already scheduled :)

Just pending the CI shooting us in the foot all the time.

**Comment by MarijnS95** [comment]
@hrydgard The [ndk-glue 0.5.0 release](https://github.com/rust-windowing/android-ndk-rs/releases/tag/ndk-glue-0.5.0) was made 5 days ago :)
