### ISSUE TITLE
 compile error 

### ISSUE THREAD

**Issue by andrewpedia** [rust-windowing/android-ndk-rs#205]
cargo build --target x86_64-linux-android

.............................

 = note: /usr/bin/ld: cannot find -llog
          collect2: error: ld returned 1 exit status

**Comment by MarijnS95** [comment]
You should use `cargo apk` which sets up the compiler and linker before internally calling something similar to `cargo build --target <your architecture>-linux-android`.

**Comment by andrewpedia** [comment]
please more details ,thanks

**Comment by andrewpedia** [comment]
Did you mean I should first type command : cargo  apk , then cargo build ?

**Comment by MarijnS95** [comment]
You should first read the readme, it is explained there.

**Comment by andrewpedia** [comment]
As the readme said , I should compile project with cargo apk build ?

**Comment by andrewpedia** [comment]
I kinda not follow your mean
