### ISSUE TITLE
Why does ndk-sys not use the jni-sys types?

### ISSUE THREAD

**Issue by laptou** [rust-windowing/android-ndk-rs#208]
For example, I want to use `ndk_sys::ANativeWindow_fromSurface` inside of a JNI method, and I have to do pointer casts in order to make it compile. Why does `ndk_sys` hav its own copies of all of the JNI types?

```
pub extern "C" fn vulkanSurfaceInit(env: &JNIEnv, surface: jobject) -> () {
	  let window = unsafe {
	      ndk_sys::ANativeWindow_fromSurface(
	          env.get_native_interface() as *mut _,
	          surface as *mut _,
	      )
	  };
	  
	  let window = match std::ptr::NonNull::new(window) {
	      Some(x) => x,
	      None => {
	          error!("ANativeWindow_fromSurface was null");
	          return;
	      }
	  };
	  
	  let window = unsafe { ndk::native_window::NativeWindow::from_ptr(window) };
	// ...
}
```

**Comment by MarijnS95** [comment]
> Why

Most likely this simply wasn't given any thought when the initial bindings were generated through `bindgen`. Not a deliberate choice.

Fortunately it is straightforward to replace all those types, try this and let us know if it resolves your problem: https://github.com/MarijnS95/android-ndk-rs/compare/ndk-sys-jni.

Coincidentally compiling `ndk-sys` on my machine for `aarch64-linux-android` takes `1.20s`, adding the `jni-sys` crate bumps it up to `1.29s`, but removing all autogenerated code for these types brings it back down to `1.19s` again.

**Comment by laptou** [comment]
This worked perfectly for me. Thank you so much! 

Are you going to merge this change into `master`?

**Comment by MarijnS95** [comment]
@laptou Of course! I was waiting for your test result before buttoning up the changes and opening a PR (for peer review, we don't merge straight to master :stuck_out_tongue:).

**Comment by tiann** [comment]
When there is a new release for this?

**Comment by tiann** [comment]
Many thanks for your hard work!

**Comment by MarijnS95** [comment]
Looks like the release CI got unblocked, ndk 0.6.0 is available now: https://crates.io/crates/ndk

**Comment by tiann** [comment]
I tried in my project, it works perfect!
