### ISSUE TITLE
Adding support for more NDK libraries

### ISSUE THREAD

**Issue by JasperDeSutter** [rust-windowing/android-ndk-rs#22]
I'm wondering what the best approach is to adding support to more Android NDK libraries.
Currently ndk-sys only links to 'libandroid', which is the only lib needed for basic windowing support.
Some other libraries that could be useful:
* libaaudio: can be used to add support to [cpal](https://github.com/RustAudio/cpal) for example to add android support to Rust game engines.
* libjnigraphics: writing into Android bitmaps can be useful for image processing libraries.
* libcamera2ndk: Android camera support would be very nice to have in the Rust ecosystem.
* libmediandk: needed for reading images from camera, media codecs could be useful too.

Could these be included in this repo, perhaps as different crates to still have the modularity? It would lead to this repo being something more in the line of winapi, and less just for native activity glue support.
The other option is maintaining these other libraries separately as an 'ndk-libs' library or individually as needed. This might lead to a very fragmented approach towards configuring API level (see below) and documentation.
What is your take on this @dvc94ch?

Other questions arise such as how to deal with Android API levels? This is needed because native API's only become available at certain android versions.
Cargo features map pretty well to this IMO. It would be nice that all these libs would use the same system for that.

Some ideal usage of these libs would look like this:

```toml
ndk = { version = "0.1.0", features = ["api-27", "camera", "media"] }
```
or
```toml
ndk = { version = "0.1.0", features = ["api-27"] }
ndk-camera = { version = "0.1.0", features = ["api-27"] }
ndk-media = { version = "0.1.0", features = ["api-27"] }
```

Maybe cargo-apk can also check these levels to match 'min_sdk_version' for example.

**Comment by dvc94ch** [comment]
Maybe we should follow what jni-bindgen does, so that developers don't have to remember which library uses which feature names. [0]

If I understand correctly those libraries you mentioned are just thin wrappers around the jni api's. I don't understand enough about the jni, but it seems it leads to converting java::String to CString to String, so maybe the better approach would be to use the jni directly.

- [0] https://github.com/MaulingMonkey/jni-bindgen/tree/master/jni-android-sys#build-features

**Comment by JasperDeSutter** [comment]
Using the same system makes sense, so then it just boils down to "api-level-X" cargo features.

These other libraries are not based on JNI though, except for 'jnigraphics' which just adds some extra functionality to the JNI exposed Bitmap type.
There are only a couple libraries like this available in NDK, see https://developer.android.com/ndk/guides/stable_apis. In contrast to others (including OpenGL/Vulkan and OpenSL) which are already available in the Rust ecosystem because they are not Android specific.
The proposal is to add those couple Android NDK-only libraries to android-ndk-rs as well, because they are not available yet.

**Comment by dvc94ch** [comment]
Sounds good to me

**Comment by francesca64** [comment]
Is this issue resolved?

**Comment by JasperDeSutter** [comment]
@francesca64  most of this is done. The system for enabling library modules and api-levels is implemented, but more libraries can still be added. The biggest one to do still is NDK camera2. I have an implementation in WIP, but I still need to find the correct approach towards metadata handling.
IMO we can start using different issues for adding more libraries / enhancing current supported ones, and close this one.
