### ISSUE TITLE
What's the valid approach to create `android/content/Context`?

### ISSUE THREAD

**Issue by wusyong** [rust-windowing/android-ndk-rs#221]
Sorry if this is out of the scope of this repo. But I saw there's an example about JNI which also has some context usage, so I would like to see if this might be related.
I tried to create a `android/content/Context` object, but both `new_object` and `new_object_unchecked` failed with same message.
It there another way or the actual correct way to create a class object?

Here's how I used `new_object`:
```rs
    let class = env.find_class("android/content/Context").unwrap();
    let context = env.new_object(class, "()V", &[]).unwrap();
```

Here's how I used `new_object_unchecked`:
```rs
    let class = env.find_class("android/content/Context").unwrap();
    let method = env.get_method_id(class, "<init>", "()V").unwrap();
    let context = env.new_object_unchecked(class, method, &[]).unwrap();
```

And here's the same error I got:
```
A/com.example.w: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: can't make objects of type android.content.Context: 0x70e2aaf0
    java_vm_ext.cc:579]     in call to NewObjectA
```

**Comment by dvc94ch** [comment]
Why do you keep closing issues? There isn't really a good solution yet.

Activity is a subclass of Context. If your code is being called from kotlin you need to pass the activity to your rust code, if you're using cargo-apk you can get it from ndk-glue for now.
