### ISSUE TITLE
`cargo-apk` should respect `[env]` section in cargo config

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-windowing/android-ndk-rs#230]
https://doc.rust-lang.org/cargo/reference/config.html#env

I fully expected cargo to just pass this to every child process, but apparently it doesn't and it's up to the child process to set these.

For our project, we'd like to keep the setup for android as basic / minimal as possible, so we're vendoring our android sdk, so to remove some steps in our process, and to not pollute global environment variables, it would be nice if cargo-apk could respect environment variables set in the cargo config file (or any other checked in config file, though this seems most natural). 

That way we can use `[env]` to set up our `ANDROID_SDK_ROOT` and `ANDROID_NDK_ROOT` like normal.

**Comment by MarijnS95** [comment]
We implemented this in https://github.com/rust-windowing/android-ndk-rs/pull/249 and released it as `cargo-apk 0.9.0` in https://github.com/rust-windowing/android-ndk-rs/pull/269 :tada:
