### ISSUE TITLE
cargo apk says there are no platforms installed

### ISSUE THREAD

**Issue by jakbyte** [rust-windowing/android-ndk-rs#26]
`cargo apk` says that `Android SDK has no platforms installed.`, yet `ls $ANDROID_SDK_ROOT/platforms` lists multiple.

**Comment by dvc94ch** [comment]
which version are you using? `$ANDROID_SDK_ROOT` is ignored, `$ANDROID_SDK_HOME` or `$ANDROID_HOME` are used.

**Comment by dvc94ch** [comment]
whats in `$ANDROID_NDK_HOME/platforms`?

**Comment by MarijnS95** [comment]
I ran into a similar issue a few weeks back. As it turned out, the selected NDK version was an empty folder, hence ndk-build not finding the `platforms/android-{}` subfolder for the appropriate API version.

**Comment by jakbyte** [comment]
`$ANDROID_NDK_HOME` has a directory named `21.1.6352462` which has the `platforms` directory inside.

**Comment by dvc94ch** [comment]
Can you provide more information? The code is very straightforward, can you figure out what assumption is wrong and let me know so that I can fix it?

**Comment by jakbyte** [comment]
I installed the NDK through Android Studio into `$ANDROID_SDK_HOME/ndk`. I set `$ANDROID_NDK_HOME` to this location.

Here's the directory structure:
```
sdk/
├── ndk
│   └── 21.1.6352462
│       └── platforms
```

**Comment by dvc94ch** [comment]
So platforms is empty? Why?

**Comment by jakbyte** [comment]
No, platforms isn't empty.

**Comment by MarijnS95** [comment]
@jakbyte What folders are exactly in there? And what folders are under `$ANDROID_HOME/platforms/`? The intersection of those two must give at least one `android-{}` folder, otherwise this error is thrown.

@dvc94ch The "fix" that is likely distinct errors when `sdk/platforms` is empty, `ndk/xxx/platforms/` is empty, and another one when none of the SDKs found in `ndk/xxx/platforms/` match an SDK in `sdk/platforms`.

**Comment by jakbyte** [comment]
1. Here's a list of platforms in both `platforms` directories.

```
sdk:
android-25/  android-26/  android-29/

ndk:
android-16/  android-18/  android-21/  android-23/  android-26/  android-28/
android-17/  android-19/  android-22/  android-24/  android-27/  android-29/
```

2. Both have `android-29` directories.

**Comment by dvc94ch** [comment]
@jakbyte this is the only place where that error is thrown:
```rust
        let platforms_dir = sdk_path.join("platforms");
        let platforms: Vec<u32> = std::fs::read_dir(&platforms_dir)
            .or(Err(NdkError::PathNotFound(platforms_dir)))?
            .filter_map(|path| path.ok())
            .filter(|path| path.path().is_dir())
            .filter_map(|path| path.file_name().into_string().ok())
            .filter(|name| name.starts_with("android-"))
            .filter_map(|name| name[8..].parse::<u32>().ok())
            .filter(|level| {
                ndk_path
                    .join("platforms")
                    .join(format!("android-{}", level))
                    .exists()
            })
            .collect();

        if platforms.len() < 1 {
            return Err(NdkError::NoPlatformFound);
        }
```
Can you add some `println!` to show what `ndk_path` and `sdk_path` are? I'll open an issue for improving logging and error messages.

**Comment by jakbyte** [comment]
It works when I run it with  `ANDROID_NDK_HOME=$ANDROID_NDK_HOME/21.1.6352462` (the version I have installed which also has the platforms directory inside), so either that's what your supposed to set `$ANDROID_NDK_HOME` to or you should look for the latest version inside `$ANDROID_NDK_HOME`.

**Comment by JasperDeSutter** [comment]
This the way I use it:
```
ANDROID_SDK_HOME="~/Android/Sdk";
ANDROID_NDK_HOME="~/Android/Sdk/ndk/21.1.6363665";
```
It depends on how you installed the NDK, you seem to have a side-by-side install like me. I used the android studio SDK manager, but the CLI tool `sdkmanager` also has the option to install this package.
You can also have 'ndk-bundle' package installed. In that case the path is `$ANDROID_SDK_HOME/ndk-bundle`

**Comment by dvc94ch** [comment]
I installed the ndk with my system package manager. I'd rather not add too many assumptions about how the ndk is installed.

**Comment by jakbyte** [comment]
It works for me now, and the current implementation is right AFAIK, so I'm closing this.
