### ISSUE TITLE
"...\\aarch64-linux-android-ar.cmd doesn't exists" when running "cargo apk run" 

### ISSUE THREAD

**Issue by julhe** [rust-windowing/android-ndk-rs#29]
Just wanted to check out the example with:
```
$ cargo apk run
Error: Path "C:\\Users\\Julian\\AppData\\Local\\Android\\Sdk\\ndk\\21.0.6113669\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android-ar.cmd" doesn't exist.
```
Checking that directory "aarch64-linux-android-ar.cmd" infact doesn't exist (but aarch64-linux-android-ar.exe does).

Any ideas?

**Comment by MarijnS95** [comment]
https://github.com/rust-windowing/android-ndk-rs/blob/977ac7ebb6bf80b1e3a7f1df4b26f88f1d272199/ndk-build/src/ndk.rs#L195-L198

Could this be a typo here? I don't recall seeing `.cmd` as extension for binaries, is that a Mac thing?

**Comment by dvc94ch** [comment]
cmd is the equivalent of sh on Linux.

**Comment by MarijnS95** [comment]
@dvc94ch `cmd` is the shell on Windows, `.exe` is the extension for executable binaries - Linux has no extension for that. I think this should be dropped or replaced with `.exe`.

**Comment by julhe** [comment]
> 
> 
> https://github.com/rust-windowing/android-ndk-rs/blob/977ac7ebb6bf80b1e3a7f1df4b26f88f1d272199/ndk-build/src/ndk.rs#L195-L198
> 
> Could this be a typo here? I don't recall seeing `.cmd` as extension for binaries, is that a Mac thing?
> 
> (EDIT: Same for `fn clang()` at
> 
> https://github.com/rust-windowing/android-ndk-rs/blob/977ac7ebb6bf80b1e3a7f1df4b26f88f1d272199/ndk-build/src/ndk.rs#L174-L177
> )
> 
> EDIT2: Afaik Windows can perfectly execute files without `.exe`, it'll append that itself (unless it's a shell feature 🤷). Can you try removing the `ext` completely and see whether that works?

Well, I changed that, but It's still trying to find that file with an .cmd extention...

**Comment by dvc94ch** [comment]
If it's a script it needs the cmd extension, if it's a binary the exe extension. I guess clang is a script wrapper around the actual binary on windows while at is the actual binary

**Comment by MarijnS95** [comment]
Forgot to add that the extension for batch files on Windows is `.bat`. I'll have to install the NDK on Windows to see what it's like, but I doubt they are wrapping compiler utilities in such an odd way.

@julhe Afaik you need to reinstall `cargo-apk` locally for that change to propagate, did you do that (using something like `cargo install --offline --path=cargo-apk`)?

**Comment by julhe** [comment]
@MarijnS95 so I managed it to build by chaing the ext in the ``fn toolchain_bin``` to .exe, but I also had to remove the "++" at
https://github.com/rust-windowing/android-ndk-rs/blob/977ac7ebb6bf80b1e3a7f1df4b26f88f1d272199/ndk-build/src/ndk.rs#L186

Now It complains that it can't find "..\\libndk_examples.so" ...
```
$ cargo apk run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Error: Path "\\\\?\\C:\\Users\\Julian\\wkspaces\\PUBLIC\\android-ndk-rs\\target\\aarch64-linux-android\\debug\\libndk_examples.so" doesn't exist.
```

**Comment by MarijnS95** [comment]
> @MarijnS95 so I managed it to build by chaing the ext in the ``fn toolchain_bin``` to .exe, but I also had to remove the "++" at
> https://github.com/rust-windowing/android-ndk-rs/blob/977ac7ebb6bf80b1e3a7f1df4b26f88f1d272199/ndk-build/src/ndk.rs#L186

Ah "great", I recently added that bit. Allow me to check on Windows if/why there's no `clang++` there, when it clearly is on Linux, and submit a fix for that.

> Now It complains that it can't find "..\libndk_examples.so" ...
> 
> ```
> $ cargo apk run
>     Finished dev [unoptimized + debuginfo] target(s) in 0.04s
> Error: Path "\\\\?\\C:\\Users\\Julian\\wkspaces\\PUBLIC\\android-ndk-rs\\target\\aarch64-linux-android\\debug\\libndk_examples.so" doesn't exist.
> ```

Now that's odd, can you confirm what files are in that folder? I doubt the cross-compiler emits them under the wrong name...

**Comment by julhe** [comment]
> 
> 
> > @MarijnS95 so I managed it to build by chaing the ext in the ``fn toolchain_bin``` to .exe, but I also had to remove the "++" at
> > https://github.com/rust-windowing/android-ndk-rs/blob/977ac7ebb6bf80b1e3a7f1df4b26f88f1d272199/ndk-build/src/ndk.rs#L186
> 
> Ah "great", I recently added that bit. Allow me to check on Windows if/why there's no `clang++` there, when it clearly is on Linux, and submit a fix for that.

Problem was that it would add the "++" to the extention. 😄 

> 
> > Now It complains that it can't find "..\libndk_examples.so" ...
> > ```
> > $ cargo apk run
> >     Finished dev [unoptimized + debuginfo] target(s) in 0.04s
> > Error: Path "\\\\?\\C:\\Users\\Julian\\wkspaces\\PUBLIC\\android-ndk-rs\\target\\aarch64-linux-android\\debug\\libndk_examples.so" doesn't exist.
> > ```
> 
> Now that's odd, can you confirm what files are in that folder? I doubt the cross-compiler emits them under the wrong name...

```
Julian@*** MINGW64 ~/wkspaces/PUBLIC/android-ndk-rs/target/aarch64-linux-android/debug (master)
$ ls
build/  deps/  examples/  incremental/  libndk_examples.d  libndk_examples.rlib
```

**Comment by MarijnS95** [comment]
> Problem was that it would add the "++" to the extention.

Ah I see now, `clang.exe++` :joy:. If you remove the `.exe` completely it should still work: can you confirm that?

> ```
> Julian@*** MINGW64 ~/wkspaces/PUBLIC/android-ndk-rs/target/aarch64-linux-android/debug (master)
> $ ls
> build/  deps/  examples/  incremental/  libndk_examples.d  libndk_examples.rlib
> ```

Make sure that you build the example with something like `cargo apk run -p ndk-examples --examples`. `crate-type = ["cdylib"]` is not specified for `[lib]` so it only builds the rlib.

**Comment by julhe** [comment]
@MarijnS95 okay, now it actually builds. But it will give me this message at the end.
``` 'lib/arm64-v8a/libhello_world.so'...
Verifying alignment of \\?\C:\Users\Julian\wkspaces\PUBLIC\android-ndk-rs\target\debug\apk\examples\hello_world.apk (4)...
      49 AndroidManifest.xml (OK - compressed)
     967 lib/arm64-v8a/libhello_world.so (OK - compressed)
Verification succesful
'\\?\C:\Users\Julian\wkspaces\PUBLIC\android-ndk-rs\target\debug\apk\examples'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
The system cannot find the path specified.
Error: Command '\\\\?\\C:\\Users\\Julian\\AppData\\Local\\Android\\Sdk\\build-tools\\29.0.3\\apksigner.bat sign --ks C:\\Users\\Julian\\.android\\debug.keystore --ks-pass pass:android \\\\?\\C:\\Users\\Julian\\wkspaces\\PUBLIC\\android-ndk-rs\\target\\debug\\apk\\examples\\hello_world.apk' had a non-zero exit code.
```
And the generated APK seems to have a invalid certificate:
```
$ adb install hello_world.apk
adb: failed to install hello_world.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1557884914.tmp/base.apk: Attempt to get length of null array]
Performing Streamed Install
```

**Comment by MarijnS95** [comment]
@julhe apologies it took this long to get to Windows and run the tests for you. The two referenced PRs should solve it all.

@dvc94ch A couple observations on Windows, using NDK r21c (21.2.6472646):

- You are right, `.cmd` _is_ a batch extension too (and a pretty commnon one, too);
- Only clang has wrapper scripts;
  - The scripts with `.cmd` use batch (cmd), the scripts without extension use `/bin/bash`, so we _need_ to use the `.cmd` one to be safe.
- All other toolchain binaries are normal executables with `.exe` extension;
- `.exe` is not necessary when files are called normally, but `ndk-build` checks their existence specifically. This is a sane thing to do, so I updated the extension rather than remove it and the check.

I doubt this differs from earlier NDK versions but it's worth to check. Is there a minimum version you want to support that we can check?

**Comment by dvc94ch** [comment]
@MarijnS95 thanks for your help on this!

> I doubt this differs from earlier NDK versions but it's worth to check. Is there a minimum version you want to support that we should validate this on too?

I think I researched this one for a while. The conclusion I came too is encoded in the min-sdk-version provided in the manifest.

**Comment by MarijnS95** [comment]
> @MarijnS95 thanks for your help on this!

My pleasure, it's quite fun rooting around in Rust, learning as I go :)

> I think I researched this one for a while. The conclusion I came too is encoded in the min-sdk-version provided in the manifest.

I couldn't really trace this back. It appears `min_sdk_version` is never initialized but instead defaults to `23`, but `target_sdk_version` defaults to the result of `default_platform()` which is simply the highest corresponding version between the selected SDK and NDK.

That means the aim is to enable support for all NDKs that support API level `23`? Or rather, accept fallbacks if anyone still even uses those? I don't plan on testing and fixing this for all NDK revisions except an upcoming PR for `20.1` which is the latest available through `sdkmanager`. Though most users will likely install something more recent through Android Studio or by downloading the zip.

**Comment by Kaiser1989** [comment]
Super fast bugfix:
Just copy "aarch64-linux-android-ar.exe" and rename it to "aarch64-linux-android-ar.cmd"

**Comment by dvc94ch** [comment]
@MarijnS95 it doesn't really make sense to support lower sdk versions than 23. The min-sdk-version means that it won't be available for download in the play store I think

**Comment by dvc94ch** [comment]
Seems resolved to me

**Comment by MarijnS95** [comment]
@dvc94ch Doesn't make sense to me either, and I don't think it's worth finding and testing some ancient NDK that supports API 23. We'll get any such issues fixed in due time, if they are reported.

Fine to close as resolved 🎉
