### ISSUE TITLE
Fails to build when target is moved

### ISSUE THREAD

**Issue by clay53** [rust-windowing/android-ndk-rs#302]
For my workspace, I have my target moved to another folder.
```
[build]
target-dir = "../../../../../Nextcloud_Cargo/git/github/clay53/tutor_engine"
```
Trying to build with `cargo apk build`, I get this error (nothing else):
```
Error: No such file or directory (os error 2)
 ```
Can workaround by creating a symlink to `../../../../../Nextcloud_Cargo/git/github/clay53/tutor_engine` it in the top-level workspace directory.

**Comment by MarijnS95** [comment]
https://github.com/rust-windowing/android-ndk-rs/issues/102#issuecomment-765356880
https://github.com/dvc94ch/cargo-subcommand/pull/7
https://github.com/dvc94ch/cargo-subcommand/commit/7166d6f45a42105decb0244a61be0e746377269c

**Comment by clay53** [comment]
> @clay53 Is this still an issue?

no

**Comment by MarijnS95** [comment]
Thanks for confirming!
