### ISSUE TITLE
Reducing the size of build (stripping)?

### ISSUE THREAD

**Issue by Animeshz** [rust-windowing/android-ndk-rs#355]
The hello_world example produces shared library of 19MB (maybe reasonable for the std lib), and adding simple library of axum increases it to 42MB.

Doesn't seem good, seems like a lot of unused symbols are packed into the library, is there way to strip it before packaging?

**Comment by MarijnS95** [comment]
@Animeshz This is the default for Rust debug libraries/binaries. You can use [standard `Cargo.toml` configuration](https://doc.rust-lang.org/cargo/reference/profiles.html#strip) to control this behaviour.
