### ISSUE TITLE
Cargo apk returns `Error: Failed to parse config` when Cargo version inherits from workspace

### ISSUE THREAD

**Issue by Nicolas-Ferre** [rust-windowing/android-ndk-rs#359]
Since Rust 1.64.0, it is possible to [inherit some package properties from the workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacepackage-table).
This feature seems not yet supported by Cargo apk for the `package.version` property.

For example, running the command `cargo apk run --package my_package` in a workspace returns the following error:
```text
Error: Failed to parse config.

Caused by:
    invalid type: map, expected a string for key `package.version` at line 3 column 21
```
Where the `Cargo.toml` file of `my_package` is:
```toml
[package]
name = "my_package"
version.workspace = true
```

**Comment by MarijnS95** [comment]
We just started using these internally too, and are working on parser support for it.

**Comment by MarijnS95** [comment]
- https://github.com/dvc94ch/cargo-subcommand/pull/23
- https://github.com/dvc94ch/cargo-subcommand/pull/24
- https://github.com/rust-windowing/android-ndk-rs/pull/360
