### ISSUE TITLE
Error Linking | armv7a-linux-androideabi28-clang | Linux Mint

### ISSUE THREAD

**Issue by sotrh** [rust-windowing/android-ndk-rs#38]
I've been trying to run gfx-rs/wgpu-rs on Android, and I've run into a linking error with version 0.1.0 of the `ndk` package.

I've created a repository that replicates the issue.

https://github.com/sotrh/wgpu-on-android

I've attached an the stderr output of `cargo apk run` as well.
[error.txt](https://github.com/rust-windowing/android-ndk-rs/files/4738606/error.txt)

Let me know if I can provide more information.

**Comment by MarijnS95** [comment]
Hi!

The problem, at least for me when building your application, is `name = "android"``. This results in your target library being named `libandroid.so`, which is the name of the library containing the symbols it's missing.
Fwiw I see `wgpu-on-android/target/aarch64-linux-android/debug/deps/libandroid.so: file not recognized: File truncated` instead.

**Comment by sotrh** [comment]
I've updated the crate name, but the error still persists. My guess is that I'm missing a native package, but I don't know which one.

**Comment by dvc94ch** [comment]
If you rename the crate, you probably still have libandroid.so in your target folder. Can you try manually removing the file or doing a clean build?

**Comment by sotrh** [comment]
It's compiling now
