### ISSUE TITLE
Please post a new release

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-windowing/android-ndk-rs#44]
We've been running into a bunch of issue here last night when collaborating with somebody, that we've submitted fixes for (and that got merged into master - #33, #32, #32, #30, #20, #18). It would be really helpful for our workflows to get a new default `cargo apk` when installing it.

**Comment by Jasper-Bekkers** [comment]
I think we have one issue outstanding (#43) that we'd like to get in first.

**Comment by msiglreith** [comment]
I would be happy if #45 makes it in as well (:

**Comment by dvc94ch** [comment]
I don't have permission to make a release, you'll have to bug @Osspial  or @goddessfreya or @francesca64

**Comment by francesca64** [comment]
I unfortunately was never given permission... I reached out to @Osspial in the hopes of getting that amended, but no luck so far. @goddessfreya is also MIA on Github (hope she's doing well!), but I haven't tried contacting her directly. I will pursue this further.

@dvc94ch would you like release permission as well? I doubt we're ever going to have the problem of having *too* much autonomy, though I guess I'm not yet in any position to be making promises.

**Comment by dvc94ch** [comment]
That would be great, thanks for looking into it

**Comment by Jasper-Bekkers** [comment]
Did we end up finding anybody to do this, or did everybody end up disappearing? 👀

**Comment by francesca64** [comment]
@Jasper-Bekkers I certainly won't be disappearing, and I've successfully made contact, so I'll likely be able to resolve this soon. @Osspial is active as well, so you can always try your luck at notification roulette, but her inbox is surely flooded.

**Comment by Jasper-Bekkers** [comment]
@francesca64 That's good to hear 😊🥳

**Comment by Osspial** [comment]
I’ve published patch releases of `cargo-apk` and `ndk-build`, and given publisher permissions to @francesca64 and @dvc94ch. Sorry it’s taken so long for me to manage this.
