### ISSUE TITLE
undefined symbol: ANativeActivity_onCreate

### ISSUE THREAD

**Issue by Kaiser1989** [rust-windowing/android-ndk-rs#46]
Can someone help me, i'm trying to make my project run on android for several days now. Trying this and that, but i don't get it working. 
I'm able to build my apk for 3 android targets, but when trying to run the apk on my emulator (x86), i always get following error in logcat:

> java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/rust.morph_it-yGX1RVocUqIQEKTw8rXDQw==/lib/x86/libmorph_it.so": undefined symbol: ANativeActivity_onCreate

My cargo.toml contains these dependencies:
```
ndk = "0.1.0"
ndk-glue = "0.1.0"
```

and my lib.rs has following functions:
```
#[cfg(target_os = "android")]
ndk_glue::ndk_glue!(main);

use ndk_glue::Event;

pub fn main() {
    if let Some(event) = ndk_glue::poll_events() {
        match event {
            Event::Start => {
                println!("started");
            },
            _ => {
                println!("other");
            }
        }
    }
}
```

Am i missing anything? Do i use a wrong android version? Do i have to add some other libs?
Thanks for your help!

**Comment by Kaiser1989** [comment]
got it, sorry...

**Comment by MarijnS95** [comment]
@Kaiser1989 Would you mind to post the solution regardless, for posterity? A popular XKCD pops up: https://xkcd.com/979/

**Comment by Kaiser1989** [comment]
It was probably a setup problem with my toolchains. 
Installing cargo apk by just running install cargo apk did not work on my windows host machine. I got several errors where ndk batch files could not be found. After fixing them, i got the message above. It compiled correctly but there was no entry point for android to load the ndk functions.

Solution:
Remove everything with ndk from dependencies, like old android_glue.
use this dependency:
```
[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { git = "https://github.com/rust-windowing/android-ndk-rs" }
```
INFO: "0.1.0" did not work, there were same changes and there is no docu

Install cargo apk with:
`cargo install --git https://github.com/rust-windowing/android-ndk-rs cargo-apk`

And in my lib, i just use:
```
#[cfg(target_os = "android")]
#[cfg_attr(target_os = "android", ndk_glue::main(backtrace))]
pub fn main() {
 ...
}

```
