### ISSUE TITLE
Android Crash: Reason: Input dispatching timed out

### ISSUE THREAD

**Issue by Kaiser1989** [rust-windowing/android-ndk-rs#47]
Trying to run a simplest hello world program crashes on android with:

`Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 2.)`

My toml:
```
[package]
name = "hello-world"
version = "0.1.0"
authors = ["XXXXX <xxxxxx@xxxxxx.xxx>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { git = "https://github.com/rust-windowing/android-ndk-rs" }

[package.metadata.android]
package_name = "hello-world"
build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android"]
```

and my lib.rs:
```
#[cfg(target_os = "android")]
#[cfg_attr(target_os = "android", ndk_glue::main(backtrace))]
pub fn main() {
    println!("Hello world");
}
```

It seems that some input event queue is not handled correctly. 

Version:
rustc 1.44.1
android build tools: 29.0.3

**Comment by Kaiser1989** [comment]
Ok i got it:

We have to check the input_queue und finish all input events to prevent this error:

```
if let Some(input_queue) = ndk_glue::input_queue().as_ref() {
    while let Some(event) = input_queue.get_event() {
        println!("{:?}", event);
        input_queue.finish_event(event, true);
    }
}
```

So my first thought was a simple loop (that never dies) where first checking for input events and then polling android events. But there comes the next problem:

```
while true {

    // handle input
    if let Some(input_queue) = ndk_glue::input_queue().as_ref() {
        while let Some(event) = input_queue.get_event() {
            println!("{:?}", event);
            input_queue.finish_event(event, true);
        }
    }

    // handle android events
    if let Some(event) = ndk_glue::poll_events() {
       // handle stuff
    } else {
        // THIS IS NEVER CALLED, POLL EVENTS IS BLOCKING
    }
}
```

but poll_events is blocking and never returns None. This way we again get a input dispatch timeout.

Internally poll_events is calling "libc::read" which is a blocking read access.

**Comment by MarijnS95** [comment]
@Kaiser1989 The example is barebones and indeed - as you already found - requires an event loop.

You should only poll for events when the looper returns events are available on the pipe. See the winit implementation:

https://github.com/rust-windowing/winit/blob/3d5d05eac7d23c78e4e66789563b3d4285e3a4eb/src/platform_impl/android/mod.rs#L107

**Comment by Kaiser1989** [comment]
I tried winit first, and it crashed with the exact same error. That's why i started trying my own loop.

**Comment by dvc94ch** [comment]
If you're certain there's a problem with winit you should open an issue, but @MarijnS95 explained why your example doesn't work. You should only poll events when the looper says there are events available in the pipe
