### ISSUE TITLE
Cannot build example

### ISSUE THREAD

**Issue by stefan2904** [rust-windowing/android-ndk-rs#48]
I am new to the Rust world, and I just tried to build the example.

Following the commands in the README:

```
cd ndk-examples
cargo apk build
```
(`cargo apk run` has the same problem.)

Unfortunately it does not work:

> % cargo apk build
>    Compiling proc-macro2 v1.0.18
>    Compiling unicode-xid v0.2.1
>    Compiling syn v1.0.33
>    Compiling serde v1.0.114
>    Compiling log v0.4.8
>    Compiling libc v0.2.72
>    Compiling cfg-if v0.1.10
>    Compiling ndk-sys v0.1.0 (/home/smore/projects/android-ndk-rs/ndk-sys)
>    Compiling jni-sys v0.3.0
>    Compiling lazy_static v1.4.0
>    Compiling android_log-sys v0.1.2
>    Compiling quote v1.0.7
>    Compiling toml v0.5.6
>    Compiling proc-macro-crate v0.1.4
>    Compiling thiserror-impl v1.0.20
>    Compiling derivative v2.1.1
>    Compiling num_enum_derive v0.4.3
>    Compiling ndk-macro v0.1.0 (/home/smore/projects/android-ndk-rs/ndk-macro)
>    Compiling thiserror v1.0.20
>    Compiling num_enum v0.4.3
>    Compiling ndk v0.1.0 (/home/smore/projects/android-ndk-rs/ndk)
>    Compiling ndk-glue v0.1.0 (/home/smore/projects/android-ndk-rs/ndk-glue)
>    Compiling ndk-examples v0.1.0 (/home/smore/projects/android-ndk-rs/ndk-examples)
>     Finished dev [unoptimized + debuginfo] target(s) in 14.35s
>
> Error: Path "/home/smore/projects/android-ndk-rs/target/aarch64-linux-android/debug/libndk_examples.so" doesn't exist.
> cargo apk build  54.83s user 2.89s system 396% cpu 14.554 total

Is there a step missing?

Thanks!

---

I am running `cargo 1.44.1 (88ba85757 2020-06-11)` on the latest Ubuntu.

**Comment by adals** [comment]
+1 same here on MacOs

$ cargo -V
cargo 1.46.0-nightly (fede83ccf 2020-07-02)
$ rustc -V 
rustc 1.46.0-nightly (8ac1525e0 2020-07-07)

**Comment by msiglreith** [comment]
`cargo apk build --example hello_world` should be working.
You might need to install `cargo-apk` directly from the source (`cargo install --path .` inside the `cargo-apk` directory)

**Comment by MarijnS95** [comment]
https://github.com/rust-windowing/android-ndk-rs/issues/29#issuecomment-635395518 I commented the same here. How about cleaning this up, such that `ndk-examples` either is the example (without empty lib), or move it into `ndk-glue/examples` and do away with `ndk-examples/`?

**Comment by dvc94ch** [comment]
Seems resolved
