### ISSUE TITLE
ndk-glue 0.1.1 violates semver

### ISSUE THREAD

**Issue by francesca64** [rust-windowing/android-ndk-rs#52]
The `ndk_glue!` macro was removed in #37, which is a breaking change. The latest release only bumps the patch version, so this results in surprise downstream breakage.

**Comment by francesca64** [comment]
I yanked ndk-glue 0.1.1, but since #53 could lead to further breaking changes, let's hold off on re-releasing until after that's resolved.

**Comment by MarijnS95** [comment]
@francesca64 You might want to yank `ndk` and `ndk-sys` as well as there's currently a type incompatibility:

```rust
   Compiling ndk-sys v0.1.1
   Compiling ndk v0.1.1
   Compiling ndk-glue v0.1.0
error[E0308]: mismatched types
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\ndk-glue-0.1.0\src\lib.rs:147:42
    |
147 |     callbacks.onSaveInstanceState = Some(on_save_instance_state);
    |                                          ^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found `usize`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, *mut u64) -> _`
                  found fn item `unsafe extern "C" fn(_, *mut usize) -> _ {on_save_instance_state}`
```

**Comment by francesca64** [comment]
@MarijnS95 ah, thanks! You spared me having to investigate that. They've now been yanked.

**Comment by MarijnS95** [comment]
@francesca64 Thanks for the quick reply, our app is in working order again :tada:
