### ISSUE TITLE
Enable immersive mode only available on main thread

### ISSUE THREAD

**Issue by Kaiser1989** [rust-windowing/android-ndk-rs#56]
I want to add the android immersive mode, meaning hiding the UI-Buttons of android.

I've written a simple jni function to hide the buttons. Running on app startup is working fine, but only until sending the app to background. The method should be called on every resume event, as the original view state is set to default.

But the ndk event seem to be handle on a different thread, leading to following error:

> 2020-08-05 16:23:29.535 6736-6758/rust.morph_it E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: rust.morph_it, PID: 6736
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7313)
        at android.view.ViewRootImpl.recomputeViewAttributes(ViewRootImpl.java:3462)
        at android.view.View.setSystemUiVisibility(View.java:22634)

The immersive function is called via jni:
```
#[cfg(target_os = "android")]
fn enable_immersive() {
    let vm_ptr = ndk_glue::native_activity().vm();
    let vm = unsafe { jni::JavaVM::from_raw(vm_ptr) }.unwrap();
    let env = vm.attach_current_thread().unwrap();
    let activity = ndk_glue::native_activity().activity();
    let window = env.call_method(activity, "getWindow", "()Landroid/view/Window;", &[]).unwrap().l().unwrap();
    let view = env.call_method(window, "getDecorView", "()Landroid/view/View;", &[]).unwrap().l().unwrap();
    let view_class = env.find_class("android/view/View").unwrap();
    let flag_fullscreen = env.get_static_field(view_class, "SYSTEM_UI_FLAG_FULLSCREEN", "I").unwrap().i().unwrap();
    let flag_hide_navigation = env.get_static_field(view_class, "SYSTEM_UI_FLAG_HIDE_NAVIGATION", "I").unwrap().i().unwrap();
    let flag_immersive_sticky = env.get_static_field(view_class, "SYSTEM_UI_FLAG_IMMERSIVE_STICKY", "I").unwrap().i().unwrap();
    let flag = flag_fullscreen | flag_hide_navigation | flag_immersive_sticky;
    env.call_method(view, "setSystemUiVisibility", "(I)V", &[jni::objects::JValue::Int(flag)]).unwrap();
}
```

Is there any way to call this function on every resume event on the main thread?

**Comment by Kaiser1989** [comment]
Ok after some investigation, the exception is raised randomly. Swapping the application to background and foreground sometimes cause this issue.

Maybe there is some race condition when calling javaVM. I got it fixed by:

```
#[cfg(target_os = "android")]
fn enable_immersive() {
    let vm_ptr = ndk_glue::native_activity().vm();
    let vm = unsafe { jni::JavaVM::from_raw(vm_ptr) }.unwrap();
    let env = vm.attach_current_thread().unwrap();
    let activity = ndk_glue::native_activity().activity();
    let window = env.call_method(activity, "getWindow", "()Landroid/view/Window;", &[]).unwrap().l().unwrap();
    let view = env.call_method(window, "getDecorView", "()Landroid/view/View;", &[]).unwrap().l().unwrap();
    let view_class = env.find_class("android/view/View").unwrap();
    let flag_fullscreen = env.get_static_field(view_class, "SYSTEM_UI_FLAG_FULLSCREEN", "I").unwrap().i().unwrap();
    let flag_hide_navigation = env.get_static_field(view_class, "SYSTEM_UI_FLAG_HIDE_NAVIGATION", "I").unwrap().i().unwrap();
    let flag_immersive_sticky = env.get_static_field(view_class, "SYSTEM_UI_FLAG_IMMERSIVE_STICKY", "I").unwrap().i().unwrap();
    let flag = flag_fullscreen | flag_hide_navigation | flag_immersive_sticky;
    match env.call_method(view, "setSystemUiVisibility", "(I)V", &[jni::objects::JValue::Int(flag)]) {
        Err(_) => println!("Failed to enable immersive mode"),
        _ => {}
    }
    env.exception_clear();
}

```
It's important to clear the exception, otherwise java will raise it when vm returns to java context after env is dropped.

It seems a bit weird, but it depends on where exactly the function call is placed within the event handling. Just try some different places (calling early in event handling works best for me). 

With upper code, the immersive mode is not set when the call fails, but the application keeps running, so on the next resume, the buttons are hidden again. Maybe use a flag to indicate the failure, so you can try again to call immersive mode in the next frame.

**Comment by francesca64** [comment]
Was this closed intentionally?

**Comment by Kaiser1989** [comment]
> Was this closed intentionally?

Yeah, I'm not able to reproduce this, or more specific, find a setting where the call will fail for sure. 
I checked the calling thread: It's always the same one. So it's not the problem the error is telling us and what I mentioned in the title.
This seems to be some android stuff. Therefore I wasn't sure if this is the right place for this issue.

If you have any idea, let me know. If you want to reopen it again, then I will do.
I just wanted to leave a "solution" for this problem if someone else will find this from search...
