### ISSUE TITLE
Git tagging when releases are made

### ISSUE THREAD

**Issue by lex148** [rust-windowing/android-ndk-rs#60]
Would you please consider making git tags when releases are made?
It would really help to see what the source was for a given release.

**Comment by francesca64** [comment]
Of course! I'll add tags for existing releases as well. I'll take care of this when I add a CHANGELOG as part of #59.

**Comment by francesca64** [comment]
All existing releases (aside from "legacy"/pre-0.5.0 cargo-apk) have now been tagged: https://github.com/rust-windowing/android-ndk-rs/releases
