### ISSUE TITLE
cargo-apk does not search shared libraries in all known paths

### ISSUE THREAD

**Issue by katyo** [rust-windowing/android-ndk-rs#65]
I think `cargo-apk` should also search shared libraries in paths which known by compiler, i.e. which was listed using "-L" command-line argument.

In my original PR for previous generation of this tool I added function `libs_search_path_from_args` for that:
https://github.com/rust-windowing/android-rs-glue/pull/260/files#diff-85629c31011b4a1ea5f77781f277ab4bR336
https://github.com/rust-windowing/android-rs-glue/pull/260/files#diff-85629c31011b4a1ea5f77781f277ab4bR461-R478

Currently as I see only "deps" directory is listed for search libs:
https://github.com/rust-windowing/android-ndk-rs/blob/bb11c390893c965f5b765675f87a101a03cb013a/cargo-apk/src/apk.rs#L92

This needs to avoid problems with third shared libraries needed for bindings and so (for ex. katyo/oboe-rs#5).

**Comment by katyo** [comment]
It seems currently get compiler args isn't so easy.
I does not understand how to do it.

**Comment by msiglreith** [comment]
One option I see would to manually iterate through the `output` files generated when build scripts are executed during the invocation of cargo. These would be located in `target/<target_arch>/<profile>/deps/<dep>/output` and contain the println output from the build scripts, which would also include the library paths.

There might be a better option but I think this would resolve the issue if I understand it correctly.

**Comment by katyo** [comment]
> One option I see would to manually iterate through the `output` files generated when build scripts are executed during the invocation of cargo. These would be located in `target/<target_arch>/<profile>/deps/<dep>/output` and contain the println output from the build scripts, which would also include the library paths.
> 
> There might be a better option but I think this would resolve the issue if I understand it correctly.

Sounds reasonable and relatively easy to implement it. Maybe, I will try this idea.

**Comment by francesca64** [comment]
Fixed by #68
