### ISSUE TITLE
Build failure on macOS

### ISSUE THREAD

**Issue by MoAlyousef** [rust-windowing/android-ndk-rs#75]
Hello

Running cargo install cargo-apk on macOS Catalina 10.15.4 x86_64 and window 10 x86_64 (using the msvc toolchain), both of which using rustc stable 1.41, fails with several errors (from a macOS):
[error.txt](https://github.com/rust-windowing/android-ndk-rs/files/5272487/error.txt)

Most errors involve:
^ `*const i8` cannot be shared between threads safely

Is there a minimum Rust version or are there any platform restrictions?

Thank you

**Comment by msiglreith** [comment]
Hi 👋,

could you verify your toolchain installation?
`std::process::Command` implements `Send` for unix systems since [1.25](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1250-2018-03-29), which seems to be the issue from the log.

**Comment by MoAlyousef** [comment]
I have rustc 1.41 which seems to fail the build. I tried running ```cargo install cargo-apk``` in a github actions instance and it builds without errors:
https://github.com/MoAlyousef/android-test/actions/runs/271232777

I guess I'll have to update my toolchain.
