### ISSUE TITLE
Error: Android SDK has no platforms installed.

### ISSUE THREAD

**Issue by 5mirok5** [rust-windowing/android-ndk-rs#76]
Hi there!
OS: Windows 10
When I'm trying to compile my project with `cargo apk run` I get this error:
``` Error: Android SDK has no platforms installed. ```

But I've installed platforms:
![image](https://user-images.githubusercontent.com/42434556/94143095-64e1a580-fe80-11ea-9b5d-215bda1ee756.png)

**Comment by 5mirok5** [comment]
I've fixed it somehow. Now I get another trouble. When I build my application, I got:

```
    Finished release [optimized] target(s) in 2.16s                                                                                                                                                                                                                            Error: Path "C:\\Users\\Vladislav\\project\\android\\target\\aarch64-linux-android\\release\\libandroid.so" doesn't exist.                                                                                                                                                     PS C:\Users\Vladislav\project\android>   
```

**Comment by msiglreith** [comment]
Hi!
what path have you set for `ANDROID_SDK_ROOT`?
For example mine is: `"C:\Users\msigl\AppData\Local\Android\Sdk"`, which contains `platform/android-xx` as  in you example

**Comment by 5mirok5** [comment]
> 
> 
> Hi!
> what path have you set for `ANDROID_SDK_ROOT`?
> For example mine is: `"C:\Users\msigl\AppData\Local\Android\Sdk"`, which contains `platform/android-xx` as in you example
> 
> edit: too slow :D

Anyway thanks for reply :)
I just had to reboot my PC. But now I got an error after successful compilation:
`Error: Path "C:\\Users\\Vladislav\\project\\android\\target\\aarch64-linux-android\\release\\libandroid.so" doesn't exist.  `

**Comment by msiglreith** [comment]
One possibility could be that crate type is not set as in https://github.com/rust-windowing/android-ndk-rs#hello-world or https://github.com/rust-windowing/android-ndk-rs/blob/master/ndk-examples/Cargo.toml.

**Comment by 5mirok5** [comment]
> 
> 
> One possibility could be that crate type is not set as in https://github.com/rust-windowing/android-ndk-rs#hello-world or https://github.com/rust-windowing/android-ndk-rs/blob/master/ndk-examples/Cargo.toml.
> 
> Depends a bit on the setup of your project, the example in the README and in `ndk-examples` are slightly different but both approaches should work fine.

My Cargo.toml is

`[package]
name = "android_test"
version = "0.1.0"
authors = ["Francis <mirok45@gmail.com>"]
edition = "2018"
crate-type = ["lib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version="*" }
ndk = { version = "*", features = ["trace"] }
jni = "0.17"

[lib]
crate-type = ["lib", "cdylib"]
`

And `main.rs`:

`
use ndk::trace;

#[cfg_attr(target_os = "android", ndk_glue::main(backtrace = "on"))]
fn main() {
    let _trace;
    if trace::is_trace_enabled() {
        _trace = trace::Section::new("ndk-rs example main").unwrap();
    }
    println!("hello world");
}
`

But I still get:
`Error: Path "C:\\Users\\Vladislav\\project\\android_test\\target\\aarch64-linux-android\\debug\\libandroid_test.so" doesn't exist.`

**Comment by 5mirok5** [comment]
Seems APK is builded anyway :)

Another silly question - how to sign my APP when I build it from cargo apk? I can't install my APK:
`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl712044386.tmp/base.apk: Attempt to get length of null array]      `

**Comment by 5mirok5** [comment]
I've finally installed it via [Uber Apk Signer](https://github.com/patrickfav/uber-apk-signer). But it crashes.
