### ISSUE TITLE
NativeActivity: NativeActivity LoadNativeLibrary failed: dlopen failed: cannot locate symbol "cargo_apk_injected_glue_add_sender" referenced 

### ISSUE THREAD

**Issue by huaji249** [rust-windowing/android-ndk-rs#78]
NativeActivity: NativeActivity LoadNativeLibrary failed: dlopen failed: cannot locate symbol "cargo_apk_injected_glue_add_sender" referenced

**Comment by dvc94ch** [comment]
What version of cargo apk are you using?

**Comment by huaji249** [comment]
version = "0.4.3"

**Comment by dvc94ch** [comment]
Maybe you should try 0.5.1

**Comment by huaji249** [comment]
remove android_glue in dependencies
