### ISSUE TITLE
aarch64-linux-android23-clang doesn't exist

### ISSUE THREAD

**Issue by Kaiden42** [rust-windowing/android-ndk-rs#93]
Hello, I was trying to build the hello_world example and got stuck to following error:
```
$ cargo apk run --example hello_world
Error: Path "/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang" doesn't exist.
```

I've installed the android-sdk and android-ndk on my Linux Mint 20 using apt:
```
$ sudo apt install android-sdk google-android-ndk-installer
```

And have set `ANDROID_SDK_ROOT` and `ANDROID_NDK_ROOT` to:
```
export ANDROID_SDK_ROOT="/usr/lib/android-sdk"
export ANDROID_NDK_ROOT="/usr/lib/android-ndk"
export PATH="${PATH}:${ANDROID_SDK_ROOT}/tools/:${ANDROID_SDK_ROOT}/platform-tools/"
```

When listing the contend of the directory, it only shows a `clang` binary but not an `aarch64-linux-android23-clang` binary.
```
$ ll /usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/
drwxr-xr-x 2 root root 4,0K Okt 12  2016 arm64-v8a
drwxr-xr-x 2 root root 4,0K Okt 12  2016 armeabi
drwxr-xr-x 2 root root 4,0K Okt 12  2016 armeabi-v7a
drwxr-xr-x 2 root root 4,0K Okt 12  2016 armeabi-v7a-hard
-rwxr-xr-x 1 root root  13K Okt 12  2016 asan_device_setup
-rwxr-xr-x 1 root root  39M Okt 12  2016 clang
-rwxr-xr-x 1 root root  39M Okt 12  2016 clang++
-rwxr-xr-x 1 root root  18M Okt 12  2016 clang-tidy
-rwxr-xr-x 1 root root 479K Okt 12  2016 FileCheck
-rwxr-xr-x 1 root root 3,0M Okt 12  2016 llvm-as
-rwxr-xr-x 1 root root 2,5M Okt 12  2016 llvm-dis
-rwxr-xr-x 1 root root 3,8M Okt 12  2016 llvm-link
drwxr-xr-x 2 root root 4,0K Okt 12  2016 mips
drwxr-xr-x 2 root root 4,0K Okt 12  2016 mips64
drwxr-xr-x 2 root root 4,0K Okt 12  2016 x86
drwxr-xr-x 2 root root 4,0K Okt 12  2016 x86_64
```

I was using the latest master branch of the example and cargo-apk.
What am I missing?

**Comment by dvc94ch** [comment]
I think after installing the ndk you need to install at least one android platform.

**Comment by MarijnS95** [comment]
That `bin/` directory looks too empty, and the timestamps are equally worrying: `Okt 12  2016`; the packaged NDK in those repositories is ancient.

You should install a recent version (r21 or r22) through the sdk manager or download it from the website.

**Comment by MarijnS95** [comment]
@Kaiden42 Did you resolve this issue.

**Comment by Kaiden42** [comment]
Oh, I'm sorry. I forgot to share the status. Thanks for the reminder.

Yes, I had now tried with a newer NDK version from the official website. It seems like the installer from Google in the package manager is really badly outdated. It's working now with ne newer version.

I thank you for your help.

**Comment by MarijnS95** [comment]
@Kaiden42 good news, thank you for updating!
