### ISSUE TITLE
Question: how to set android:launchMode with cargo apk

### ISSUE THREAD

**Issue by maxded** [rust-windowing/android-ndk-rs#95]
Not sure if I'm just completely missing something but I can't seem to figure out how to set the `android:launchMode` from my cargo.toml using cargo apk. 

```
[package.metadata.android]
launch_mode = "singleTask" 
```
or 

```
[[package.metadata.android.activity_metadatas]]
name = "launchMode"
value = "singleTask"
```
don't seem to work.

Tried a bunch of different ways but can't get it to work. Is it even supported or, like I said, am I missing something. :)

**Comment by MarijnS95** [comment]
The code to embed this in `<activity>` still has to be built:

https://github.com/rust-windowing/android-ndk-rs/blob/b5844d84c73accee77490f597e88c31e5831b5b6/ndk-build/src/manifest.rs#L87-L91

`activity_metadatas` creates a `<meta-data android:name="launchMode" android:value="singleTask" />` which is not what you want. Should instead be `android:launchMode="singleTask"` directly in the `<activity>` element.

I guess it's worth asking whether this XML `format!` code can be turned into a proper serialize + deserialize mechanism? If possible one that can be parsed directly from `toml` to make it easy to "just model" manifest layout in some struct and have it automatically converted?
