### ISSUE TITLE
pointer_id missing

### ISSUE THREAD

**Issue by MarnixKuijs** [rust-windowing/android-ndk-rs#97]
According to the docs if I wanted identifiers  that stay the same I should use `pointer_id`. `pointer_id` however doesn't seem to be a function. I did notice that there is `pointer_id_for`, but is just commented out? I was curious about the status of `pointer_id` and what the reason is that `pointer_id_for` is commented out.

I am trying to do some work that requires multitouch and `pointer_index` is not good enough for me because I need the id's to be the consistent, that is the reason I want to use `pointer_id`. Are there alternatives for doing multitouch with id's for fingers that are consistent?

![image (1)](https://user-images.githubusercontent.com/44985093/99953003-dc4c8c00-2d80-11eb-816a-b38351df768c.png)

**Comment by MarijnS95** [comment]
I guess it's intended to use `Pointer::pointer_id` and `HistoricalPointer::pointer_id`? These are safe wrappers, you can retrieve them with the `.pointers()` function right below, or `.pointer_at_index(index).pointer_id()`.

**Comment by MarnixKuijs** [comment]
Aaaah okay the link that is placed in the [docs]https://docs.rs/ndk/0.2.1/ndk/event/struct.MotionEvent.html#method.pointer_index was broken and I couldn't find the function elsewhere, turns out I just didn't look in the right place
