### ISSUE TITLE
dlopen failed: cannot locate symbol "_ZTVN10__cxxabiv117__class_type_infoE"

### ISSUE THREAD

**Issue by Wicpar** [rust-windowing/android-ndk-rs#99]
Hi,

I am trying to build my lib for android, and cannot seem to solve this. Apparently cargo-apk already links the -lc++_static ...
i tried adding stdc++ as static_bundle in build.rs as well but it doesn' t change anything...

I cannot pinpoint the origin of the link, and the symbol doesn' t even exist in the .so when i decompile it with ghydra...
_ZTVN10__cxxabiv117__class_type_infoE is a phantom...

Has anyone come across this ?

**Comment by msiglreith** [comment]
Hi, sorry for the repsonding so late!

I personally didn't try linking with c++ libraries so far. IIRC the oboe bindings are using it, maybe it's helpful: https://github.com/katyo/oboe-rs/blob/master/oboe-sys/build.rs
Do you have some minimal sample or a repository to reproduce it?

**Comment by Wicpar** [comment]
turns out all the projects crash in the same manner, every single example project... it's an issue with the new android version, at least it's the last remaning explainantion I have. i just ditched oboe and used aaudio directly by forking cpal.

**Comment by MarijnS95** [comment]
@Wicpar Iirc some symbols are missing from `c++_static` but are available in `c++_shared`. Perhaps that's worth a try?

**Comment by Wicpar** [comment]
could be, i didn't try with the shared lib.

**Comment by imxood** [comment]
in my android11 project, it is ok after add c++_shared lib.

![image](https://user-images.githubusercontent.com/14890680/147398441-9a34030f-c7fb-431c-8137-ce69763042ed.png)

**Comment by torokati44** [comment]
Thanks for the tip, @imxood.
It seems to me however, that `cargo-apk` ignores this `build.rs`?
And after I start a "regular" cargo build for the same target - which then fails because the C/C++ cross-toolchain is not set up right for `cc` -, that somehow "repairs it", and from then on, `cargo-apk` also links to `c++_shared`?!
I also need it (mostly) for `oboe` BTW...
